CREATE WAREHOUSE P10_WH
WAREHOUSE_SIZE = 'XSMALL';

USE WAREHOUSE P10_WH;
CREATE DATABASE P10_DB;
CREATE SCHEMA P10_DB.CUSTOMER_SCHEMA;
USE DATABASE P10_DB;

USE SCHEMA CUSTOMER_SCHEMA;


-- ============================================================

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE P10_CUSTOMER_STAGE
    FILE_FORMAT = CSV_FORMAT;


SHOW STAGES;

LIST @P10_CUSTOMER_STAGE;


-- CREATE SCD TYPE 3 DIMENSION
-- ============================================================

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE3 (
    CUSTOMER_KEY        NUMBER AUTOINCREMENT,
    CUSTOMER_ID         NUMBER,
    CUSTOMER_NAME       VARCHAR(100),
    CITY                VARCHAR(100),
    STATE               VARCHAR(100),
    CURRENT_MEMBERSHIP  VARCHAR(50),
    PREVIOUS_MEMBERSHIP VARCHAR(50),
    SEGMENT             VARCHAR(50)
);

DESC TABLE DIM_CUSTOMER_TYPE3;


--=====================================================
CREATE OR REPLACE TABLE CUSTOMER_INITIAL_STAGE (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    MEMBERSHIP VARCHAR(50),
    SEGMENT VARCHAR(50)
);
COPY INTO CUSTOMER_INITIAL_STAGE
FROM @P10_CUSTOMER_STAGE/customer_initials.csv
FILE_FORMAT = CSV_FORMAT;

INSERT INTO DIM_CUSTOMER_TYPE3
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    SEGMENT
FROM CUSTOMER_INITIAL_STAGE;

select * from customer_initial_stage;
select * from dim_customer_type3;


-- =================task5,6 Apply scd type 3====================================


CREATE OR REPLACE TABLE CUSTOMER_UPDATES_STAGE (
    CUSTOMER_ID       NUMBER,
    CUSTOMER_NAME     VARCHAR(100),
    CITY              VARCHAR(100),
    STATE             VARCHAR(100),
    MEMBERSHIP        VARCHAR(50),
    SEGMENT            VARCHAR(50),
    EFFECTIVE_DATE    DATE
);

COPY INTO CUSTOMER_UPDATES_STAGE
FROM @P10_CUSTOMER_STAGE/customer_updates.csv
FILE_FORMAT = CSV_FORMAT;

SELECT *
FROM CUSTOMER_UPDATES_STAGE
ORDER BY CUSTOMER_ID;
--================================

UPDATE DIM_CUSTOMER_TYPE3 T
SET
    PREVIOUS_MEMBERSHIP = T.CURRENT_MEMBERSHIP,
    CURRENT_MEMBERSHIP  = U.MEMBERSHIP,
    CITY                = U.CITY,
    STATE               = U.STATE,
    CUSTOMER_NAME       = U.CUSTOMER_NAME,
    SEGMENT             = U.SEGMENT
FROM CUSTOMER_UPDATES_STAGE U
WHERE T.CUSTOMER_ID = U.CUSTOMER_ID;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE3
ORDER BY CUSTOMER_ID;

--TASK 8: DEMONSTRATE SCD TYPE 3

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE3
WHERE CUSTOMER_ID = 101;

-- ============================================================
-- PROJECT 10
-- TASK 9: CREATE SCD TYPE 6 DIMENSION
CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE6 (
    CUSTOMER_KEY         NUMBER AUTOINCREMENT,
    CUSTOMER_ID          NUMBER,
    CUSTOMER_NAME        VARCHAR(100),
    CITY                 VARCHAR(100),
    STATE                VARCHAR(100),
    CURRENT_MEMBERSHIP   VARCHAR(50),
    PREVIOUS_MEMBERSHIP  VARCHAR(50),
    HISTORICAL_MEMBERSHIP VARCHAR(50),
    SEGMENT              VARCHAR(50),
    EFFECTIVE_DATE       DATE,
    EXPIRY_DATE          DATE,
    IS_CURRENT           BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE6;

--TASK 10: LOAD INITIAL TYPE 6 RECORDS

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    NULL,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01'::DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_INITIAL_STAGE;

-- VERIFY INITIAL TYPE 6 DATA

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID;

-- ============================================================

-- TASK 11,12
-- APPLY SCD TYPE 6 CHANGES

UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-03-31'::DATE,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;


-- 2. Create the new version
INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    T.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES_STAGE U
JOIN DIM_CUSTOMER_TYPE6 T
    ON U.CUSTOMER_ID = T.CUSTOMER_ID
WHERE U.CUSTOMER_ID = 101
  AND T.IS_CURRENT = FALSE
  AND T.EXPIRY_DATE = '2026-03-31'::DATE;


UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-04'::DATE,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    T.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES_STAGE U
JOIN DIM_CUSTOMER_TYPE6 T
    ON U.CUSTOMER_ID = T.CUSTOMER_ID
WHERE U.CUSTOMER_ID = 103
  AND T.IS_CURRENT = FALSE
  AND T.EXPIRY_DATE = '2026-04-04'::DATE;


UPDATE DIM_CUSTOMER_TYPE6
SET
    EXPIRY_DATE = '2026-04-09'::DATE,
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE6
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    U.CUSTOMER_ID,
    U.CUSTOMER_NAME,
    U.CITY,
    U.STATE,
    U.MEMBERSHIP,
    T.CURRENT_MEMBERSHIP,
    U.MEMBERSHIP,
    U.SEGMENT,
    U.EFFECTIVE_DATE,
    '9999-12-31'::DATE,
    TRUE
FROM CUSTOMER_UPDATES_STAGE U
JOIN DIM_CUSTOMER_TYPE6 T
    ON U.CUSTOMER_ID = T.CUSTOMER_ID
WHERE U.CUSTOMER_ID = 104
  AND T.IS_CURRENT = FALSE
  AND T.EXPIRY_DATE = '2026-04-09'::DATE;


SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE6
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

--TASK 14 Current Customer Report=============================================
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;

--task 15 TASK 15 — Point-in-Time Historical Query=====================

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CURRENT_MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER_TYPE6
WHERE CUSTOMER_ID = 101
  AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;

  -- ============================================================
-- PROJECT 10
-- TASK 16: SCD TYPE 3 VS SCD TYPE 6
-- ============================================================

SELECT
    'SCD TYPE 3' AS SCD_TYPE,
    'YES' AS CURRENT_VALUE,
    'YES' AS PREVIOUS_VALUE,
    'NO' AS HISTORICAL_ROWS,
    'NO' AS EFFECTIVE_DATE,
    'NO' AS EXPIRY_DATE,
    'NO' AS IS_CURRENT

UNION ALL

SELECT
    'SCD TYPE 6' AS SCD_TYPE,
    'YES' AS CURRENT_VALUE,
    'YES' AS PREVIOUS_VALUE,
    'YES' AS HISTORICAL_ROWS,
    'YES' AS EFFECTIVE_DATE,
    'YES' AS EXPIRY_DATE,
    'YES' AS IS_CURRENT;


-- ============================================================
-- TASK 17: RECORD COUNT VALIDATION
-- ============================================================


SELECT
    'SCD TYPE 3 RECORD COUNT' AS METRIC,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_TYPE3

UNION ALL

SELECT
    'SCD TYPE 6 RECORD COUNT' AS METRIC,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6

UNION ALL

SELECT
    'SCD TYPE 6 CURRENT RECORD COUNT' AS METRIC,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = TRUE

UNION ALL
SELECT
    'SCD TYPE 6 HISTORICAL RECORD COUNT' AS METRIC,
    COUNT(*) AS RECORD_COUNT
FROM DIM_CUSTOMER_TYPE6
WHERE IS_CURRENT = FALSE;