create warehouse p18_wh
warehouse_size = 'xsmall';
use warehouse p18_wh;

CREATE DATABASE IF NOT EXISTS CLEANROOM_SHARED_DB;
CREATE SCHEMA IF NOT EXISTS CLEANROOM_SHARED_DB.PARTNER_TELEMETRY;
USE DATABASE CLEANROOM_SHARED_DB;
USE SCHEMA PARTNER_TELEMETRY;

create table BRONZE_RETAIL_TRANSACTIONS
(
    POS_ID      VARCHAR,
    TIMESTAMP TIMESTAMP_TZ,
    HASHED_EMAIL VARCHAR,
    STORE_ID VARCHAR,
    CPG_BRAND VARCHAR,
    BASKET_VALUE NUMBER(10,2),
    LOYALTY_TIER VARCHAR
);
CREATE TABLE BRONZE_AD_EXPOSURES
(
    AD_ID VARCHAR,
    TIMESTAMP TIMESTAMP_TZ,
    HASHED_EMAIL VARCHAR,
    CAMPAIGN_NAME VARCHAR,
    CHANNEL VARCHAR
);

INSERT INTO BRONZE_RETAIL_TRANSACTIONS
(
    POS_ID,
    TIMESTAMP,
    HASHED_EMAIL,
    STORE_ID,
    CPG_BRAND,
    BASKET_VALUE,
    LOYALTY_TIER
)
VALUES
('POS-1001', '2026-08-16 10:00:00 +00:00', 'a3f8c12...', 'STORE-01', 'ApexFoods', 145.50, 'GOLD'),
('POS-1002', '2026-08-16 10:15:00 +00:00', 'b9e4d56...', 'STORE-01', 'ApexFoods', 89.20, 'SILVER'),
('POS-1003', '2026-08-16 10:30:00 +00:00', 'c1a2b3c...', 'STORE-02', 'ApexFoods', 210.00, 'GOLD'),
('POS-1004', '2026-08-16 11:00:00 +00:00', 'd4e5f6a...', 'STORE-02', 'BioDrink', 35.00, 'BRONZE');

INSERT INTO BRONZE_AD_EXPOSURES
(
    AD_ID,
    TIMESTAMP,
    HASHED_EMAIL,
    CAMPAIGN_NAME,
    CHANNEL
)
VALUES
('AD-901', '2026-08-15 18:00:00 +00:00', 'a3f8c12...', 'Summer_Apex_Promo', 'Meta'),
('AD-902', '2026-08-15 19:30:00 +00:00', 'b9e4d56...', 'Summer_Apex_Promo', 'Google'),
('AD-903', '2026-08-15 20:00:00 +00:00', 'e7f8g9h...', 'Summer_Apex_Promo', 'TikTok');


SELECT COUNT(*) AS TOTAL_RETAIL_RECORDS
FROM BRONZE_RETAIL_TRANSACTIONS;

SELECT COUNT(*) AS TOTAL_AD_RECORDS
FROM BRONZE_AD_EXPOSURES;

----------------------------task 2--------------------------------
CREATE TABLE SILVER_ATTRIBUTION_MATCH
(
    POS_ID              VARCHAR,
    STORE_ID            VARCHAR,
    CAMPAIGN_NAME       VARCHAR,
    CHANNEL             VARCHAR,
    BASKET_VALUE        NUMBER(10,2),
    CONVERSION_HOURS    NUMBER
);

INSERT INTO SILVER_ATTRIBUTION_MATCH
(
    POS_ID,
    STORE_ID,
    CAMPAIGN_NAME,
    CHANNEL,
    BASKET_VALUE,
    CONVERSION_HOURS
)
SELECT
    BRT.POS_ID,
    BRT.STORE_ID,
    BAD.CAMPAIGN_NAME,
    BAD.CHANNEL,
    BRT.BASKET_VALUE,
    DATEDIFF('HOUR', BAD.TIMESTAMP, BRT.TIMESTAMP)
FROM BRONZE_RETAIL_TRANSACTIONS BRT
INNER JOIN BRONZE_AD_EXPOSURES BAD
ON BRT.HASHED_EMAIL = BAD.HASHED_EMAIL;


SELECT *
FROM SILVER_ATTRIBUTION_MATCH;

-------------TASK 3---------------------------------------

CREATE SECURE VIEW SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE AS
SELECT
    CAMPAIGN_NAME,
    CHANNEL,
    COUNT (DISTINCT POS_ID) AS CONVERTED_USER_COUNT,
    SUM(BASKET_VALUE) AS TOTAL_ATTRIBUTED_SALES,
    AVG(BASKET_VALUE) AS AVG_BASKET_VALUE
FROM SILVER_ATTRIBUTION_MATCH
GROUP BY CAMPAIGN_NAME,
CHANNEL
HAVING COUNT(DISTINCT POS_ID) >= 2;

SELECT *
FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE;

--------------------TASK 4-----------------------------------

CREATE SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE ON DATABASE CLEANROOM_SHARED_DB
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT USAGE ON SCHEMA CLEANROOM_SHARED_DB.PARTNER_TELEMETRY
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

GRANT SELECT ON VIEW
CLEANROOM_SHARED_DB.PARTNER_TELEMETRY.SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

SHOW SHARES LIKE 'SHARE_CPG_PARTNER_ANALYTICS';

---------TASK 5----------------------
CREATE MANAGED ACCOUNT CPG_READER_ACCT_01
    ADMIN_NAME = 'CPG_READER_ADMIN'
    ADMIN_PASSWORD = 'StrongPassword123!'
    TYPE = READER;

SHOW MANAGED ACCOUNTS;

ALTER SHARE SHARE_CPG_PARTNER_ANALYTICS
ADD ACCOUNTS = CPG_READER_ACCT_01;

SHOW SHARES LIKE 'SHARE_CPG_PARTNER_ANALYTICS';
SHOW GRANTS TO SHARE SHARE_CPG_PARTNER_ANALYTICS;


CREATE RESOURCE MONITOR CPG_READER_RESOURCE_MONITOR
    WITH CREDIT_QUOTA = 10
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 80 PERCENT DO NOTIFY
        ON 100 PERCENT DO SUSPEND;

        SHOW MANAGED ACCOUNTS;

SHOW RESOURCE MONITORS;


--------TASK 6---------------


USE DATABASE CLEANROOM_SHARED_DB;
USE SCHEMA PARTNER_TELEMETRY;



SHOW GRANTS TO SHARE SHARE_CPG_PARTNER_ANALYTICS;

SELECT
    (
        SELECT COALESCE(SUM(BASKET_VALUE), 0)
        FROM SILVER_ATTRIBUTION_MATCH
    ) AS SILVER_MATCH_VAL,

    (
        SELECT COALESCE(SUM(TOTAL_ATTRIBUTED_SALES), 0)
        FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
    ) AS GOLD_SHARED_VAL,

    (
        SELECT IFF(
            COUNT_IF(UPPER(COLUMN_NAME) = 'HASHED_EMAIL') = 0,
            FALSE,
            TRUE
        )
        FROM CLEANROOM_SHARED_DB.INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = 'PARTNER_TELEMETRY'
          AND TABLE_NAME = 'SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE'
    ) AS PII_EXPOSURE_FLAG,

    IFF(
        (
            SELECT COALESCE(SUM(BASKET_VALUE), 0)
            FROM SILVER_ATTRIBUTION_MATCH
        )
        =
        (
            SELECT COALESCE(SUM(TOTAL_ATTRIBUTED_SALES), 0)
            FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
        ),
        TRUE,
        FALSE
    ) AS RECONCILED_FLAG;

    SELECT
    (
        SELECT COALESCE(SUM(BASKET_VALUE), 0)
        FROM SILVER_ATTRIBUTION_MATCH
    ) AS SILVER_MATCH_VAL,

    (
        SELECT COALESCE(SUM(TOTAL_ATTRIBUTED_SALES), 0)
        FROM SECURE_GOLD_CAMPAIGN_ATTRIBUTION_PERFORMANCE
    ) AS GOLD_SHARED_VAL;