CREATE OR REPLACE WAREHOUSE P17_WH
    WAREHOUSE_SIZE = 'XSMALL';

CREATE OR REPLACE DATABASE FINANCIAL_GOVERNANCE_DB;

CREATE OR REPLACE SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE;

USE WAREHOUSE P17_WH;

USE DATABASE FINANCIAL_GOVERNANCE_DB;

USE SCHEMA WEALTH_CORE;



--==============TASK 1 — BRONZE STORAGE & ERROR ISOLATION


CREATE OR REPLACE TABLE BRONZE_BANK_PAYLOADS
(
    INGEST_ID NUMBER AUTOINCREMENT,
    PAYLOAD VARIANT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

select * from bronze_bank_payloads;


CREATE OR REPLACE TABLE QUARANTINE_GOVERNANCE_PAYLOADS
(
    INGEST_ID NUMBER AUTOINCREMENT,
    RAW_PAYLOAD STRING,
    ERROR_REASON STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO BRONZE_BANK_PAYLOADS (PAYLOAD)
SELECT PARSE_JSON(column1)
FROM VALUES
('{"txn_id":"TXN-7001","timestamp":"2026-08-15T09:00:00Z","client_id":101,"client_ssn":"999-12-3456","region":"NA","account_no":"ACT-5544","amount":250000.00,"status":"SETTLED"}'),
('{"txn_id":"TXN-7002","timestamp":"2026-08-15T09:15:00Z","client_id":102,"client_ssn":"888-98-7654","region":"EU","account_no":"ACT-7711","amount":120000.00,"status":"SETTLED"}'),
('{"txn_id":"TXN-7003","timestamp":"2026-08-15T09:30:00Z","client_id":103,"client_ssn":"777-45-6789","region":"NA","account_no":"ACT-3322","amount":450000.00,"status":"PENDING"}'),
('{"txn_id":"TXN-7004","timestamp":"2026-08-15T10:00:00Z","client_id":104,"client_ssn":"666-23-8901","region":"EU","account_no":"ACT-9988","amount":85000.00,"status":"SETTLED"}'),
('{"txn_id":"TXN-7005","timestamp":"2026-08-15T10:30:00Z","client_id":105,"client_ssn":"555-67-1234","region":"NA","account_no":"ACT-1144","amount":1000000.00,"status":"SETTLED","aml_risk_score":"LOW"}'),
('{"txn_id":"TXN-7006","timestamp":"2026-08-15T11:00:00Z","client_id":106,"client_ssn":"444-89-4321","region":"EU","account_no":"ACT-6633","amount":310000.00,"status":"SETTLED","aml_risk_score":"MEDIUM"}'),
('{"txn_id":"TXN-7007","timestamp":"2026-08-15T11:30:00Z","client_id":107,"client_ssn":"333-11-2222","region":"NA","account_no":"ACT-2211","amount":0.00,"status":"FAILED","aml_risk_score":"HIGH"}');




INSERT INTO QUARANTINE_GOVERNANCE_PAYLOADS
(
    RAW_PAYLOAD,
    ERROR_REASON
)
VALUES
(
    '{"INVALID_RAW_WIRE_PAYLOAD_UNPARSEABLE"}',
    'INVALID JSON / UNPARSEABLE PAYLOAD'
);





--TASK 2 — SILVER TABLE


CREATE OR REPLACE TABLE SILVER_BANK_TRANSACTIONS
(
    TXN_ID          VARCHAR,
    CLIENT_ID       NUMBER,
    CLIENT_SSN      VARCHAR,
    REGION          VARCHAR,
    ACCOUNT_NO      VARCHAR,
    AMOUNT          NUMBER(18,2),
    STATUS          VARCHAR,
    AML_RISK_SCORE  VARCHAR
);


INSERT INTO SILVER_BANK_TRANSACTIONS
(
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
)
SELECT
    PAYLOAD:txn_id::VARCHAR,
    PAYLOAD:client_id::NUMBER,
    PAYLOAD:client_ssn::VARCHAR,
    PAYLOAD:region::VARCHAR,
    PAYLOAD:account_no::VARCHAR,
    PAYLOAD:amount::NUMBER(18,2),
    PAYLOAD:status::VARCHAR,
    PAYLOAD:aml_risk_score::VARCHAR
FROM BRONZE_BANK_PAYLOADS;


SELECT COUNT(*) AS TOTAL_SILVER_RECORDS
FROM SILVER_BANK_TRANSACTIONS;

SELECT *
FROM SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;

CREATE ROLE IF NOT EXISTS COMPLIANCE_OFFICER;

CREATE ROLE IF NOT EXISTS NA_ANALYST;

CREATE ROLE IF NOT EXISTS EU_ANALYST;


GRANT USAGE
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE NA_ANALYST;

GRANT USAGE
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE EU_ANALYST;

GRANT USAGE
ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE COMPLIANCE_OFFICER;

GRANT USAGE
ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE NA_ANALYST;

GRANT USAGE
ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE EU_ANALYST;


GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE COMPLIANCE_OFFICER;

GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE NA_ANALYST;

GRANT SELECT
ON TABLE SILVER_BANK_TRANSACTIONS
TO ROLE EU_ANALYST;


--TASK 3 — DYNAMIC DATA MASKING

CREATE OR REPLACE MASKING POLICY MASK_SSN
AS
(
    VAL VARCHAR
)
RETURNS VARCHAR
->
CASE
    WHEN IS_ROLE_IN_SESSION('COMPLIANCE_OFFICER')
        THEN VAL
    ELSE
        '***-**-' || RIGHT(VAL,4)
END;



--------------------------------------------------------------------------------
-- MASK ACCOUNT NUMBER
--------------------------------------------------------------------------------

CREATE OR REPLACE MASKING POLICY MASK_ACCOUNT
AS
(
    VAL VARCHAR
)
RETURNS VARCHAR
->
CASE
    WHEN IS_ROLE_IN_SESSION('COMPLIANCE_OFFICER')
        THEN VAL
    ELSE
        'ACT-****'
END;



--------------------------------------------------------------------------------
-- APPLY MASKING POLICIES
--------------------------------------------------------------------------------

ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN CLIENT_SSN
SET MASKING POLICY MASK_SSN;


ALTER TABLE SILVER_BANK_TRANSACTIONS
MODIFY COLUMN ACCOUNT_NO
SET MASKING POLICY MASK_ACCOUNT;



--------------------------------------------------------------------------------
-- TEST AS NA_ANALYST
--------------------------------------------------------------------------------

USE ROLE NA_ANALYST;

SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;




------------------------------------TASK 4 — ROW ACCESS POLICY


USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROW ACCESS POLICY RAP_REGION_POLICY
AS
(
    REGION_VALUE VARCHAR
)
RETURNS BOOLEAN
->
CASE

    WHEN IS_ROLE_IN_SESSION('COMPLIANCE_OFFICER')
        THEN TRUE

    WHEN IS_ROLE_IN_SESSION('NA_ANALYST')
         AND REGION_VALUE = 'NA'
        THEN TRUE

    WHEN IS_ROLE_IN_SESSION('EU_ANALYST')
         AND REGION_VALUE = 'EU'
        THEN TRUE

    ELSE FALSE

END;



--------------------------------------------------------------------------------
-- APPLY RAP
--------------------------------------------------------------------------------

ALTER TABLE SILVER_BANK_TRANSACTIONS
ADD ROW ACCESS POLICY RAP_REGION_POLICY
ON (REGION);

USE ROLE NA_ANALYST;

SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;

USE ROLE EU_ANALYST;

SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;


USE ROLE COMPLIANCE_OFFICER;

SELECT
    TXN_ID,
    CLIENT_ID,
    CLIENT_SSN,
    REGION,
    ACCOUNT_NO,
    AMOUNT,
    STATUS,
    AML_RISK_SCORE
FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
ORDER BY TXN_ID;

select current_user();

GRANT ROLE COMPLIANCE_OFFICER TO USER FLAKESN0WING;
GRANT ROLE NA_ANALYST TO USER FLAKESN0WING;
GRANT ROLE EU_ANALYST TO USER FLAKESN0WING;
GRANT ROLE EXTERNAL_AUDITOR TO USER FLAKESN0WING;


CREATE OR REPLACE TABLE GOLD_EXTERNAL_AUDIT_AGGREGATE
(
    REGION              VARCHAR,
    TOTAL_SETTLED_VAL   NUMBER(18,2),
    SETTLED_TXN_COUNT   NUMBER,
    AVG_SETTLED_AMOUNT  NUMBER(18,2)
);



INSERT INTO GOLD_EXTERNAL_AUDIT_AGGREGATE
(
    REGION,
    TOTAL_SETTLED_VAL,
    SETTLED_TXN_COUNT,
    AVG_SETTLED_AMOUNT
)
SELECT
    REGION,
    SUM(AMOUNT),
    COUNT(*),
    ROUND(AVG(AMOUNT),2)
FROM SILVER_BANK_TRANSACTIONS
WHERE STATUS = 'SETTLED'
GROUP BY REGION;


CREATE OR REPLACE SECURE VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
AS
SELECT
    REGION,
    TOTAL_SETTLED_VAL,
    SETTLED_TXN_COUNT,
    AVG_SETTLED_AMOUNT
FROM GOLD_EXTERNAL_AUDIT_AGGREGATE;

GRANT CREATE VIEW
ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE COMPLIANCE_OFFICER;

SELECT CURRENT_ROLE();

--------------------------------------------------------------------------------
-- TEST GOLD
--------------------------------------------------------------------------------

SELECT *
FROM SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY REGION;


CREATE ROLE IF NOT EXISTS EXTERNAL_AUDITOR;


GRANT USAGE
ON DATABASE FINANCIAL_GOVERNANCE_DB
TO ROLE EXTERNAL_AUDITOR;


GRANT USAGE
ON SCHEMA FINANCIAL_GOVERNANCE_DB.WEALTH_CORE
TO ROLE EXTERNAL_AUDITOR;


GRANT SELECT
ON VIEW SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
TO ROLE EXTERNAL_AUDITOR;


USE ROLE EXTERNAL_AUDITOR;

SELECT *
FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SECURE_GOLD_EXTERNAL_AUDIT_SUMMARY
ORDER BY REGION;

--------------taks 6----------------------------
USE ROLE ACCOUNTADMIN;


SELECT

    (
        SELECT SUM(PAYLOAD:amount::NUMBER(18,2))
        FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.BRONZE_BANK_PAYLOADS
    ) AS BRONZE_GROSS_TOTAL,

    (
        SELECT SUM(AMOUNT)
        FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
    ) AS SILVER_GROSS_TOTAL,

    (
        SELECT SUM(TOTAL_SETTLED_VAL)
        FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.GOLD_EXTERNAL_AUDIT_AGGREGATE
    ) AS GOLD_GROSS_TOTAL,

    CASE
        WHEN
            (
                SELECT SUM(PAYLOAD:amount::NUMBER(18,2))
                FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.BRONZE_BANK_PAYLOADS
            )
            =
            (
                SELECT SUM(AMOUNT)
                FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
            )

        AND

            (
                SELECT SUM(TOTAL_SETTLED_VAL)
                FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.GOLD_EXTERNAL_AUDIT_AGGREGATE
            )
            =
            (
                SELECT SUM(AMOUNT)
                FROM FINANCIAL_GOVERNANCE_DB.WEALTH_CORE.SILVER_BANK_TRANSACTIONS
                WHERE STATUS = 'SETTLED'
            )

        THEN TRUE

        ELSE FALSE
    END AS RECONCILED_FLAG;


