CREATE WAREHOUSE P6_RETAIL_WH
WAREHOUSE_SIZE= 'XSMALL';

USE WAREHOUSE P6_RETAIL_WH;

CREATE DATABASE P6_RETAIL_DB;
USE DATABASE P6_RETAIL_DB;

CREATE SCHEMA P6_RETAIL_SCHEMA;
USE SCHEMA P6_RETAIL_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_STAGE;


-=======================================;
CREATE TABLE RAW_CUSTOMERS(
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    MEMBERSHIP      VARCHAR 
);

CREATE TABLE RAW_PRODUCTS (
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    BRAND           VARCHAR,
    PRICE           NUMBER
);

CREATE TABLE RAW_BRANCHES (
    BRANCH_ID       NUMBER,
    BRANCH_NAME     VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    REGION          VARCHAR,
    MANAGER_NAME    VARCHAR
);

CREATE TABLE RAW_CALENDAR(
    DATE_ID     NUMBER,
    DATES       DATE,
    DAY         NUMBER,
    DAY_NAME    VARCHAR,
    WEEK_NO     NUMBER,
    MONTH       VARCHAR,
    QUARTER     VARCHAR,
    YEAR        NUMBER,
    IS_WEEKEND  VARCHAR
);

CREATE TABLE RAW_SALES (
    SALE_ID         NUMBER,
    CUSTOMER_ID     NUMBER,
    PRODUCT_ID      NUMBER,
    BRANCH_ID       NUMBER,
    DATE_ID         NUMBER,
    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER
);


/*=================================================*/

COPY INTO RAW_CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_CALENDAR
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM RAW_CUSTOMERS;
SELECT * FROM RAW_PRODUCTS;
SELECT * FROM RAW_BRANCHES;
SELECT * FROM RAW_CALENDAR;
SELECT * FROM RAW_SALES;


/*============================================*/

create table DIM_REGION(
    REGION_ID NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR
);


INSERT INTO DIM_REGION (REGION_ID, REGION_NAME)
SELECT DISTINCT
    CASE REGION
        WHEN 'South' THEN 1
        WHEN 'West'  THEN 2
        WHEN 'North' THEN 3
        WHEN 'East'  THEN 4
    END,
    REGION
FROM RAW_BRANCHES;

select * from raw_branches;

SELECT * FROM DIM_REGION;
/*===========CITY=================*/


CREATE TABLE DIM_STATE (
    STATE_ID       NUMBER PRIMARY KEY,
    STATE_NAME     VARCHAR,
    REGION_ID      NUMBER,
    FOREIGN KEY (REGION_ID) REFERENCES DIM_REGION(REGION_ID)
);
SELECT * FROM DIM_STATE;

INSERT INTO DIM_STATE (STATE_ID, STATE_NAME, REGION_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY STATE),
    STATE,
    REGION_ID
FROM (
    SELECT
        STATE,
        MAX(REGION_ID) AS REGION_ID
    FROM (
        SELECT STATE, R.REGION_ID
        FROM RAW_BRANCHES B
        JOIN DIM_REGION R
            ON B.REGION = R.REGION_NAME

        UNION ALL

        SELECT STATE, NULL AS REGION_ID
        FROM RAW_CUSTOMERS
    )
    GROUP BY STATE
) S;


SELECT * FROM DIM_STATE;





CREATE TABLE DIM_CITY (
    CITY_ID        NUMBER PRIMARY KEY,
    CITY_NAME      VARCHAR,
    STATE_ID       NUMBER,
    FOREIGN KEY (STATE_ID) REFERENCES DIM_STATE(STATE_ID)
);

INSERT INTO DIM_CITY (CITY_ID, CITY_NAME, STATE_ID)
SELECT
    ROW_NUMBER() OVER (ORDER BY CITY),
    CITY,
    S.STATE_ID
FROM (
    SELECT DISTINCT CITY, STATE
    FROM RAW_CUSTOMERS

    UNION

    SELECT DISTINCT CITY, STATE
    FROM RAW_BRANCHES
) C
JOIN DIM_STATE S
    ON C.STATE = S.STATE_NAME;

SELECT * FROM DIM_CITY ORDER BY CITY_ID;


SELECT DISTINCT CITY
FROM RAW_CUSTOMERS
WHERE CITY NOT IN (
    SELECT CITY_NAME
    FROM DIM_CITY
);

/*===================DIM-CUSTOMER======================*/
CREATE TABLE DIM_CUSTOMER (
    CUSTOMER_ID      NUMBER PRIMARY KEY,
    CUSTOMER_NAME    VARCHAR,
    MEMBERSHIP       VARCHAR,
    CITY_ID          NUMBER,
    FOREIGN KEY (CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    CITY_ID
)
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,
    CI.CITY_ID
FROM RAW_CUSTOMERS C
JOIN DIM_CITY CI
    ON C.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON C.STATE = S.STATE_NAME
   AND CI.STATE_ID = S.STATE_ID;

SELECT * FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

/*===================DIM-BRANCH======================*/
CREATE TABLE DIM_BRANCH (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR,
    MANAGER_NAME VARCHAR,
    CITY_ID NUMBER,
    FOREIGN KEY (CITY_ID) REFERENCES DIM_CITY(CITY_ID)
);

INSERT INTO DIM_BRANCH(
    BRANCH_ID,
    BRANCH_NAME,
    MANAGER_NAME,
    CITY_ID
)
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.MANAGER_NAME,
    CI.CITY_ID    
FROM RAW_BRANCHES B
JOIN DIM_CITY CI
    ON B.CITY = CI.CITY_NAME
JOIN DIM_STATE S
    ON B.STATE = S.STATE_NAME
   AND CI.STATE_ID = S.STATE_ID;

SELECT * FROM DIM_BRANCH;


/*========================================================*/
/* PRODUCT HIERARCHY                                      */
/*========================================================*/


CREATE TABLE DIM_CATEGORY(
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR
);

INSERT INTO DIM_CATEGORY(
    CATEGORY_ID,
    CATEGORY_NAME
)
SELECT
    ROW_NUMBER() OVER (ORDER BY CATEGORY),
    CATEGORY
FROM(
    SELECT DISTINCT CATEGORY
    FROM RAW_PRODUCTS
);

/*-----DIM BRAND---------*/
CREATE TABLE DIM_BRAND(
    BRAND_ID NUMBER PRIMARY KEY,
    BRAND_NAME VARCHAR,
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES DIM_CATEGORY(CATEGORY_ID)
);

INSERT INTO DIM_BRAND(
    BRAND_ID,
    BRAND_NAME,
    CATEGORY_ID
)
SELECT
    ROW_NUMBER() OVER(ORDER BY P.BRAND),
    P.BRAND,
    C.CATEGORY_ID
    FROM(
        SELECT DISTINCT BRAND, CATEGORY
        FROM RAW_PRODUCTS P
    )P
JOIN DIM_CATEGORY C
            ON P.CATEGORY = C.CATEGORY_NAME;



/*-----DIM PRODUCT---------*/

CREATE TABLE DIM_PRODUCT(
    PRODUCT_ID      NUMBER PRIMARY KEY,
    PRODUCT_NAME    VARCHAR,
    PRICE           NUMBER,
    BRAND_ID        NUMBER,
    FOREIGN KEY (BRAND_ID) REFERENCES DIM_BRAND(BRAND_ID)
);

INSERT INTO DIM_PRODUCT(
    PRODUCT_ID,
    PRODUCT_NAME,
    PRICE,
    BRAND_ID
)
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE,
    B.BRAND_ID
FROM RAW_PRODUCTS P
JOIN DIM_BRAND B
    ON P.BRAND = B.BRAND_NAME
JOIN DIM_CATEGORY C
    ON P.CATEGORY = C.CATEGORY_NAME
    AND B.CATEGORY_ID = C.CATEGORY_ID;

/*========================================================
 DATE HIERARCHY                                      
========================================================*/

CREATE TABLE DIM_DATE(
    DATE_ID     NUMBER PRIMARY KEY,
    DATES       DATE,
    DAY         NUMBER,
    DAY_NAME    VARCHAR,
    WEEK_NO     NUMBER,
    MONTH       VARCHAR,
    QUARTER     VARCHAR,
    YEAR        NUMBER,
    IS_WEEKEND  VARCHAR
);

INSERT INTO DIM_DATE(
    DATE_ID,
    DATES,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
)
SELECT
    DATE_ID,
    DATES,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
FROM RAW_CALENDAR;

SELECT * FROM DIM_DATE
ORDER BY DATE_ID;


/*========================================================
 fact sales                                      
========================================================*/

CREATE TABLE FACT_SALES(
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES DIM_CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES DIM_PRODUCT(PRODUCT_ID),
    FOREIGN KEY (BRANCH_ID) REFERENCES DIM_BRANCH(BRANCH_ID),
    FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID)
);

INSERT INTO FACT_SALES (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    S.SALE_ID,
    C.CUSTOMER_ID,
    P.PRODUCT_ID,
    B.BRANCH_ID,
    D.DATE_ID,
    S.QUANTITY,
    S.TOTAL_AMOUNT
FROM RAW_SALES S
JOIN DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON S.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON S.DATE_ID = D.DATE_ID;

SELECT * FROM FACT_SALES
ORDER BY SALE_ID;


/*========================================================
 DATE HIERARCHY - DIM YEAR                              
========================================================*/

CREATE TABLE DIM_YEAR (
    YEAR_ID NUMBER PRIMARY KEY,
    YEAR_VALUE NUMBER
);

INSERT INTO DIM_YEAR (
    YEAR_ID,
    YEAR_VALUE
)
SELECT DISTINCT
    YEAR,
    YEAR
FROM RAW_CALENDAR;

SELECT * FROM DIM_YEAR
ORDER BY YEAR_VALUE;

CREATE TABLE DIM_QUARTER (
    QUARTER_ID   NUMBER PRIMARY KEY,
    QUARTER_NAME VARCHAR,
    YEAR_ID      NUMBER,
    FOREIGN KEY (YEAR_ID) REFERENCES DIM_YEAR(YEAR_ID)
);

INSERT INTO DIM_QUARTER (
    QUARTER_ID,
    QUARTER_NAME,
    YEAR_ID
)
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY C.YEAR, C.QUARTER),
    C.QUARTER,
    Y.YEAR_ID
FROM RAW_CALENDAR C
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE;

SELECT * FROM DIM_QUARTER
ORDER BY YEAR_ID, QUARTER_ID;


/*---------------- DIM MONTH ----------------*/

CREATE TABLE DIM_MONTH (
    MONTH_ID     NUMBER PRIMARY KEY,
    MONTH_NAME   VARCHAR,
    QUARTER_ID   NUMBER,
    FOREIGN KEY (QUARTER_ID) REFERENCES DIM_QUARTER(QUARTER_ID)
);

INSERT INTO DIM_MONTH (
    MONTH_ID,
    MONTH_NAME,
    QUARTER_ID
)
SELECT DISTINCT
    ROW_NUMBER() OVER (ORDER BY C.YEAR, C.QUARTER, C.MONTH),
    C.MONTH,
    Q.QUARTER_ID
FROM RAW_CALENDAR C
JOIN DIM_QUARTER Q
    ON C.QUARTER = Q.QUARTER_NAME
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE
   AND Q.YEAR_ID = Y.YEAR_ID;

SELECT * FROM DIM_MONTH
ORDER BY MONTH_ID;


/*========================================================*/
/* DIM DATE                                                */
/*========================================================*/

CREATE TABLE DIM_DATE_NEW (
    DATE_ID      NUMBER PRIMARY KEY,
    DATES        DATE,
    DAY          NUMBER,
    DAY_NAME     VARCHAR,
    WEEK_NO      NUMBER,
    MONTH_ID     NUMBER,
    IS_WEEKEND   VARCHAR,
    FOREIGN KEY (MONTH_ID) REFERENCES DIM_MONTH(MONTH_ID)
);

INSERT INTO DIM_DATE_NEW (
    DATE_ID,
    DATES,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH_ID,
    IS_WEEKEND
)
SELECT
    C.DATE_ID,
    C.DATES,
    C.DAY,
    C.DAY_NAME,
    C.WEEK_NO,
    M.MONTH_ID,
    C.IS_WEEKEND
FROM RAW_CALENDAR C
JOIN DIM_MONTH M
    ON C.MONTH = M.MONTH_NAME
JOIN DIM_QUARTER Q
    ON C.QUARTER = Q.QUARTER_NAME
   AND M.QUARTER_ID = Q.QUARTER_ID
JOIN DIM_YEAR Y
    ON C.YEAR = Y.YEAR_VALUE
   AND Q.YEAR_ID = Y.YEAR_ID;

SELECT * FROM DIM_DATE_NEW
ORDER BY DATE_ID;

/*===============================================================
==========================================================================*/

SELECT * FROM DIM_REGION;
SELECT * FROM DIM_STATE;
SELECT * FROM DIM_CITY;
SELECT * FROM DIM_CUSTOMER;
SELECT * FROM DIM_BRANCH;

SELECT * FROM DIM_CATEGORY;
SELECT * FROM DIM_BRAND;
SELECT * FROM DIM_PRODUCT;

SELECT * FROM DIM_DATE;
SELECT * FROM FACT_SALES;

SELECT 'REGION' AS TABLE_NAME, COUNT(*) AS ROWS FROM DIM_REGION
UNION ALL
SELECT 'STATE', COUNT(*) FROM DIM_STATE
UNION ALL
SELECT 'CITY', COUNT(*) FROM DIM_CITY
UNION ALL
SELECT 'CUSTOMER', COUNT(*) FROM DIM_CUSTOMER
UNION ALL
SELECT 'BRANCH', COUNT(*) FROM DIM_BRANCH
UNION ALL
SELECT 'CATEGORY', COUNT(*) FROM DIM_CATEGORY
UNION ALL
SELECT 'BRAND', COUNT(*) FROM DIM_BRAND
UNION ALL
SELECT 'PRODUCT', COUNT(*) FROM DIM_PRODUCT
UNION ALL
SELECT 'DATE', COUNT(*) FROM DIM_DATE
UNION ALL
SELECT 'FACT_SALES', COUNT(*) FROM FACT_SALES;

DROP TABLE FACT_SALES;
DROP TABLE DIM_DATE;

ALTER TABLE DIM_DATE_NEW RENAME TO DIM_DATE;

CREATE TABLE FACT_SALES(
    SALE_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    PRODUCT_ID NUMBER,
    BRANCH_ID NUMBER,
    DATE_ID NUMBER,
    QUANTITY NUMBER,
    TOTAL_AMOUNT NUMBER,

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES DIM_PRODUCT(PRODUCT_ID),

    FOREIGN KEY (BRANCH_ID)
        REFERENCES DIM_BRANCH(BRANCH_ID),

    FOREIGN KEY (DATE_ID)
        REFERENCES DIM_DATE(DATE_ID)
);


INSERT INTO FACT_SALES (
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
)
SELECT
    S.SALE_ID,
    S.CUSTOMER_ID,
    S.PRODUCT_ID,
    S.BRANCH_ID,
    S.DATE_ID,
    S.QUANTITY,
    S.TOTAL_AMOUNT
FROM RAW_SALES S
JOIN DIM_CUSTOMER C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_BRANCH B
    ON S.BRANCH_ID = B.BRANCH_ID
JOIN DIM_DATE D
    ON S.DATE_ID = D.DATE_ID;


SELECT * FROM DIM_YEAR;

SELECT * FROM DIM_QUARTER;

SELECT * FROM DIM_MONTH;

SELECT * FROM DIM_DATE;

SELECT * FROM FACT_SALES;
/*==========================================================*/

