
-- PROJECT 19C: ENTERPRISE FINANCIAL WIRE TRANSFERS, INVENTORY BALANCES &
-- COVERAGE MATRIX


CREATE OR REPLACE WAREHOUSE P19C_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE WAREHOUSE P19C_WH;

CREATE OR REPLACE DATABASE P19C_DB;

USE DATABASE P19C_DB;

CREATE OR REPLACE SCHEMA P19C_SCHEMA;

USE SCHEMA P19C_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null');

CREATE OR REPLACE STAGE P19C_STAGE
FILE_FORMAT = CSV_FORMAT;

list @p19c_stage;





CREATE OR REPLACE TABLE RAW_WIRE_TRANSFERS
(
    TXN_ID VARCHAR,
    TXN_DATE DATE,
    SENDER_ACC VARCHAR,
    RECEIVER_ACC VARCHAR,
    AMOUNT NUMBER(18,2),
    FEE NUMBER(18,2),
    CURRENCY_RATE NUMBER(10,4),
    AUTH_METHOD VARCHAR,
    RISK_FLAG VARCHAR,
    TRANSFER_TYPE VARCHAR
);


CREATE OR REPLACE TABLE RAW_VAULT_CASH
(
    SNAPSHOT_DATE DATE,
    VAULT_ID VARCHAR,
    CURRENCY_CODE VARCHAR,
    OPENING_BALANCE NUMBER(18,2),
    CLOSING_BALANCE NUMBER(18,2),
    RESERVE_RATIO_PCT NUMBER(5,2)
);


CREATE OR REPLACE TABLE RAW_CREDIT_LIFECYCLES
(
    APP_ID VARCHAR,
    SUBMISSION_DATE DATE,
    UNDERWRITE_DATE DATE,
    RISK_APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE
);


CREATE OR REPLACE TABLE RAW_AUDIT_COVERAGE
(
    AUDIT_YEAR NUMBER,
    QUARTER VARCHAR,
    ACCOUNT_ID VARCHAR,
    AUDITOR_FIRM VARCHAR,
    COMPLIANCE_STATUS VARCHAR
);


-- 2. FILE INGESTION


COPY INTO RAW_WIRE_TRANSFERS
FROM @P19C_STAGE/raw_wire_transfers.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_VAULT_CASH
FROM @P19C_STAGE/raw_vault_cash.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_CREDIT_LIFECYCLES
FROM @P19C_STAGE/raw_credit_lifecycles.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_AUDIT_COVERAGE
FROM @P19C_STAGE/raw_audit_coverage.csv
FILE_FORMAT = CSV_FORMAT;


-- Verify 

SELECT COUNT(*) AS WIRE_ROWS
FROM RAW_WIRE_TRANSFERS;

SELECT COUNT(*) AS VAULT_ROWS
FROM RAW_VAULT_CASH;

SELECT COUNT(*) AS CREDIT_ROWS
FROM RAW_CREDIT_LIFECYCLES;

SELECT COUNT(*) AS AUDIT_ROWS
FROM RAW_AUDIT_COVERAGE;


-- TASK 1: ADVANCED JUNK DIMENSION

CREATE OR REPLACE TABLE DIM_WIRE_ATTRIBUTES
(
    ATTRIBUTE_SK NUMBER AUTOINCREMENT,
    AUTH_METHOD VARCHAR,
    RISK_FLAG VARCHAR,
    TRANSFER_TYPE VARCHAR
);


INSERT INTO DIM_WIRE_ATTRIBUTES
(
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
)
SELECT DISTINCT
    AUTH_METHOD,
    RISK_FLAG,
    TRANSFER_TYPE
FROM RAW_WIRE_TRANSFERS;


SELECT *
FROM DIM_WIRE_ATTRIBUTES
ORDER BY ATTRIBUTE_SK;


-- TASK 2: WIRE TRANSFER FACT TABLE

CREATE OR REPLACE TABLE FACT_WIRE_TRANSFERS
(
    TXN_ID VARCHAR,
    TXN_DATE DATE,
    SENDER_ACC VARCHAR,
    RECEIVER_ACC VARCHAR,
    ATTRIBUTE_SK NUMBER,
    AMOUNT NUMBER(18,2),
    FEE NUMBER(18,2),
    CURRENCY_RATE NUMBER(10,4),
    BASE_AMOUNT_USD NUMBER(18,2),
    NET_TRANSFER_VAL NUMBER(18,2)
);


INSERT INTO FACT_WIRE_TRANSFERS
(
    TXN_ID,
    TXN_DATE,
    SENDER_ACC,
    RECEIVER_ACC,
    ATTRIBUTE_SK,
    AMOUNT,
    FEE,
    CURRENCY_RATE,
    BASE_AMOUNT_USD,
    NET_TRANSFER_VAL
)
SELECT
    R.TXN_ID,
    R.TXN_DATE,
    R.SENDER_ACC,
    R.RECEIVER_ACC,
    D.ATTRIBUTE_SK,
    R.AMOUNT,
    R.FEE,
    R.CURRENCY_RATE,
    R.AMOUNT * R.CURRENCY_RATE AS BASE_AMOUNT_USD,
    (R.AMOUNT * R.CURRENCY_RATE) - R.FEE AS NET_TRANSFER_VAL
FROM RAW_WIRE_TRANSFERS R
JOIN DIM_WIRE_ATTRIBUTES D
    ON R.AUTH_METHOD = D.AUTH_METHOD
    AND R.RISK_FLAG = D.RISK_FLAG
    AND R.TRANSFER_TYPE = D.TRANSFER_TYPE;


SELECT *
FROM FACT_WIRE_TRANSFERS
ORDER BY TXN_ID;


-- TASK 3: PERIODIC VAULT SNAPSHOT


CREATE OR REPLACE TABLE FACT_VAULT_CASH_SNAPSHOT
(
    SNAPSHOT_DATE DATE,
    VAULT_ID VARCHAR,
    CURRENCY_CODE VARCHAR,
    OPENING_BALANCE NUMBER(18,2),
    CLOSING_BALANCE NUMBER(18,2),
    RESERVE_RATIO_PCT NUMBER(5,2),
    NET_DAILY_CHANGE NUMBER(18,2)
);


INSERT INTO FACT_VAULT_CASH_SNAPSHOT
(
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    NET_DAILY_CHANGE
)
SELECT
    SNAPSHOT_DATE,
    VAULT_ID,
    CURRENCY_CODE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    RESERVE_RATIO_PCT,
    CLOSING_BALANCE - OPENING_BALANCE AS NET_DAILY_CHANGE
FROM RAW_VAULT_CASH;


-- Expected grouped output

SELECT
    SNAPSHOT_DATE,
    SUM(OPENING_BALANCE) AS TOTAL_OPENING_USD_EQU,
    SUM(CLOSING_BALANCE) AS TOTAL_CLOSING_USD_EQU
FROM FACT_VAULT_CASH_SNAPSHOT
GROUP BY SNAPSHOT_DATE
ORDER BY SNAPSHOT_DATE;



-- TASK 4: LOAN APPLICATION ACCUMULATING SNAPSHOT


CREATE OR REPLACE TABLE FACT_CREDIT_APPROVAL_LIFECYCLE
(
    APP_ID VARCHAR,
    SUBMISSION_DATE DATE,
    UNDERWRITE_DATE DATE,
    RISK_APPROVAL_DATE DATE,
    DISBURSEMENT_DATE DATE,
    UNDERWRITE_DAYS NUMBER,
    RISK_APPROVAL_DAYS NUMBER,
    DISBURSEMENT_DAYS NUMBER,
    TOTAL_CYCLE_DAYS NUMBER
);


INSERT INTO FACT_CREDIT_APPROVAL_LIFECYCLE
(
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,
    UNDERWRITE_DAYS,
    RISK_APPROVAL_DAYS,
    DISBURSEMENT_DAYS,
    TOTAL_CYCLE_DAYS
)
SELECT
    APP_ID,
    SUBMISSION_DATE,
    UNDERWRITE_DATE,
    RISK_APPROVAL_DATE,
    DISBURSEMENT_DATE,
    DATEDIFF('DAY', SUBMISSION_DATE, UNDERWRITE_DATE)
        AS UNDERWRITE_DAYS,
    DATEDIFF('DAY', UNDERWRITE_DATE, RISK_APPROVAL_DATE)
        AS RISK_APPROVAL_DAYS,
    DATEDIFF('DAY', RISK_APPROVAL_DATE, DISBURSEMENT_DATE)
        AS DISBURSEMENT_DAYS,
    DATEDIFF('DAY', SUBMISSION_DATE, DISBURSEMENT_DATE)
        AS TOTAL_CYCLE_DAYS
FROM RAW_CREDIT_LIFECYCLES
WHERE DISBURSEMENT_DATE IS NOT NULL;


SELECT *
FROM FACT_CREDIT_APPROVAL_LIFECYCLE
ORDER BY APP_ID;



-- TASK 5: BOTTLENECK STAGE IDENTIFICATION


SELECT
    APP_ID,
    SUBMISSION_DATE,
    CASE
        WHEN UNDERWRITE_DATE IS NULL
            THEN 'AWAITING_UNDERWRITE'

        WHEN RISK_APPROVAL_DATE IS NULL
            THEN 'AWAITING_RISK_AUTH'

        WHEN DISBURSEMENT_DATE IS NULL
            THEN 'AWAITING_DISBURSAL'
    END AS CURRENT_BOTTLENECK
FROM RAW_CREDIT_LIFECYCLES
WHERE DISBURSEMENT_DATE IS NULL
ORDER BY APP_ID;


-- TASK 6: FACTLESS COMPLIANCE AUDIT COVERAGE


CREATE OR REPLACE TABLE FACTLESS_COMPLIANCE_AUDIT_COVERAGE
(
    AUDIT_YEAR NUMBER,
    QUARTER VARCHAR,
    ACCOUNT_ID VARCHAR,
    AUDITOR_FIRM VARCHAR,
    COMPLIANCE_STATUS VARCHAR
);


INSERT INTO FACTLESS_COMPLIANCE_AUDIT_COVERAGE
(
    AUDIT_YEAR,
    QUARTER,
    ACCOUNT_ID,
    AUDITOR_FIRM,
    COMPLIANCE_STATUS
)
SELECT
    AUDIT_YEAR,
    QUARTER,
    ACCOUNT_ID,
    AUDITOR_FIRM,
    COMPLIANCE_STATUS
FROM RAW_AUDIT_COVERAGE;


-- Accounts that processed HIGH-RISK transfers
-- and their 2026 audit coverage

SELECT
    F.SENDER_ACC AS ACCOUNT_ID,
    COUNT(*) AS HIGH_RISK_TXN_COUNT,
    CASE
        WHEN A.ACCOUNT_ID IS NOT NULL
            THEN 'AUDITED'
        ELSE 'NOT_AUDITED'
    END AS COMPLIANCE_STATUS
FROM FACT_WIRE_TRANSFERS F
LEFT JOIN FACTLESS_COMPLIANCE_AUDIT_COVERAGE A
    ON F.SENDER_ACC = A.ACCOUNT_ID
    AND A.AUDIT_YEAR = 2026
JOIN DIM_WIRE_ATTRIBUTES D
    ON F.ATTRIBUTE_SK = D.ATTRIBUTE_SK
WHERE D.RISK_FLAG = 'HIGH'
GROUP BY
    F.SENDER_ACC,
    CASE
        WHEN A.ACCOUNT_ID IS NOT NULL
            THEN 'AUDITED'
        ELSE 'NOT_AUDITED'
    END
ORDER BY ACCOUNT_ID;



-- TASK 7: RISK PROFILE REVENUE CROSS-ANALYSIS


SELECT
    D.RISK_FLAG,
    D.TRANSFER_TYPE,
    COUNT(*) AS TOTAL_TXNS,
    SUM(F.FEE) AS TOTAL_FEES,
    SUM(F.BASE_AMOUNT_USD) AS TOTAL_VOLUME_USD
FROM FACT_WIRE_TRANSFERS F
JOIN DIM_WIRE_ATTRIBUTES D
    ON F.ATTRIBUTE_SK = D.ATTRIBUTE_SK
GROUP BY
    D.RISK_FLAG,
    D.TRANSFER_TYPE
ORDER BY
    D.RISK_FLAG,
    D.TRANSFER_TYPE;


-- TASK 8: MULTI-FACT COMPREHENSIVE RECONCILIATION AUDIT


SELECT
    (
        SELECT SUM(BASE_AMOUNT_USD)
        FROM FACT_WIRE_TRANSFERS
    ) AS TOTAL_WIRE_VOL_USD,

    (
        SELECT SUM(CLOSING_BALANCE)
        FROM FACT_VAULT_CASH_SNAPSHOT
        WHERE SNAPSHOT_DATE = '2026-08-25'
    ) AS VAULT_CLOSING_USD,

    (
        SELECT COUNT(*)
        FROM FACT_CREDIT_APPROVAL_LIFECYCLE
    ) AS COMPLETED_LOAN_APPS,

    CASE
        WHEN
            (
                SELECT SUM(BASE_AMOUNT_USD)
                FROM FACT_WIRE_TRANSFERS
            ) = 2286500.00

            AND

            (
                SELECT SUM(CLOSING_BALANCE)
                FROM FACT_VAULT_CASH_SNAPSHOT
                WHERE SNAPSHOT_DATE = '2026-08-25'
            ) = 16400000.00

            AND

            (
                SELECT COUNT(*)
                FROM FACT_CREDIT_APPROVAL_LIFECYCLE
            ) = 2

        THEN TRUE
        ELSE FALSE
    END AS AUDIT_SANITY_FLAG;