CREATE WAREHOUSE P14B_WH
WAREHOUSE_SIZE ='XSMALL';
USE WAREHOUSE P14B_WH;

CREATE DATABASE P14B_DB;
USE DATABASE P14B_DB;

CREATE SCHEMA P14B_DB.P14B_SCHEMA;
USE SCHEMA P14B_SCHEMA;

--================TASK 1=============================
CREATE TABLE BRONZE_PAYMENT_PAYLOADS
(
    RAW_BRONZE VARIANT
);

INSERT INTO BRONZE_PAYMENT_PAYLOADS (RAW_BRONZE)
SELECT
PARSE_JSON('{"txn_id":"TXN-901","txn_time":"2026-07-10T10:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":50000.00,"fee_pct":2.5,"status":"APPROVED"}')
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-902","txn_time":"2026-07-10T10:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":12000.00,"fee_pct":3.0,"status":"APPROVED"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-903","txn_time":"2026-07-10T11:00:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":25000.00,"fee_pct":2.5,"status":"PENDING"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-904","txn_time":"2026-07-10T11:30:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":8500.00,"fee_pct":1.8,"status":"APPROVED"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-905","txn_time":"2026-07-10T12:00:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":45000.00,"fee_pct":3.0,"status":"DECLINED"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-906","txn_time":"2026-07-10T12:30:00Z","merchant_id":301,"merchant_name":"TechZone","card_number":"4111222233334444","amount":150000.00,"fee_pct":2.5,"status":"APPROVED"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-907","txn_time":"2026-07-10T13:00:00Z","merchant_id":303,"merchant_name":"FreshMart","card_number":"4000111122223333","amount":3200.00,"fee_pct":1.8,"status":"APPROVED"}'
)
UNION ALL
SELECT
PARSE_JSON('{"txn_id":"TXN-908","txn_time":"2026-07-10T13:15:00Z","merchant_id":302,"merchant_name":"StyleHub","card_number":"5500111122223333","amount":67000.00,"fee_pct":3.0,"status":"PENDING"}');

SELECT * FROM BRONZE_PAYMENT_PAYLOADS;


--===============TASK 2==]=================

CREATE TABLE SILVER_CLEANED_TRANSACTIONS
(
   TXN_ID                   VARCHAR(20),  
   MERCHANT_ID              NUMBER,
   MERCHANT_NAME            VARCHAR(100),
   MASKED_CARD              VARCHAR(20),
   GROSS_AMOUNT             NUMBER(12,2),    
   PROCESSING_FEE           NUMBER(12,2),
   NET_SETTLEMENT_AMOUNT    NUMBER(12,2),
   STATUS                   VARCHAR(20)
);
INSERT INTO SILVER_CLEANED_TRANSACTIONS
SELECT
    RAW_BRONZE:txn_id::VARCHAR,
    RAW_BRONZE:merchant_id::NUMBER,
    RAW_BRONZE:merchant_name::VARCHAR,
    CONCAT('XXXX-XXXX-XXXX-', RIGHT(RAW_BRONZE:card_number::VARCHAR,4)),
    RAW_BRONZE:amount::NUMBER(12,2),
    RAW_BRONZE:amount::NUMBER(12,2) * (RAW_BRONZE:fee_pct::NUMBER(5,2) /100),
    RAW_BRONZE:amount::NUMBER(12,2) - (RAW_BRONZE:amount::NUMBER(12,2) * (RAW_BRONZE:fee_pct::NUMBER(5,2) /100)),
    RAW_BRONZE:status::VARCHAR
FROM BRONZE_PAYMENT_PAYLOADS;

SELECT * FROM SILVER_CLEANED_TRANSACTIONS;


--=============----------task 3============================

CREATE TABLE GOLD_MERCHANT_SETTLEMENTS
(
    MERCHANT_ID              NUMBER,
    MERCHANT_NAME            VARCHAR(100),
    TOTAL_APPROVED_GROSS     NUMBER(12,2),
    TOTAL_GATEWAY_FEES       NUMBER(12,2),
    TOTAL_NET_PAYOUT         NUMBER(12,2),
    APPROVED_COUNT           NUMBER
);
INSERT INTO GOLD_MERCHANT_SETTLEMENTS
SELECT
    MERCHANT_ID,
    MERCHANT_NAME,
    SUM(GROSS_AMOUNT)           AS TOTAL_APPROVED_GROSS,
    SUM(PROCESSING_FEE)         AS TOTAL_GATEWAY_FEES,
    SUM(NET_SETTLEMENT_AMOUNT)  AS TOTAL_NET_PAYOUT,
    COUNT(*)                    AS APPROVED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE STATUS = 'APPROVED'
GROUP BY MERCHANT_ID, MERCHANT_NAME
ORDER BY MERCHANT_ID;
    
SELECT * FROM GOLD_MERCHANT_SETTLEMENTS;

--=============TASK 4=========================================

UPDATE SILVER_CLEANED_TRANSACTIONS
SET
    STATUS='REFUNDED'
WHERE
    MERCHANT_ID = 301 AND STATUS='APPROVED';

SELECT
    TXN_ID,
    MERCHANT_NAME,
    GROSS_AMOUNT,
    STATUS
FROM SILVER_CLEANED_TRANSACTIONS
AT (OFFSET => -60)
WHERE MERCHANT_NAME = 'TechZone'
AND STATUS = 'APPROVED';

--============TASK 5===========================

MERGE INTO SILVER_CLEANED_TRANSACTIONS AS TARGET
USING (
    SELECT TXN_ID, STATUS
    FROM SILVER_CLEANED_TRANSACTIONS
    AT (OFFSET => -300)
    WHERE MERCHANT_NAME = 'TechZone'
    AND STATUS = 'APPROVED'
) AS SOURCE
ON TARGET.TXN_ID = SOURCE.TXN_ID
WHEN MATCHED THEN
    UPDATE SET TARGET.STATUS = SOURCE.STATUS;

    SELECT
    MERCHANT_NAME,
    COUNT(CASE WHEN STATUS = 'APPROVED' THEN 1 END) AS APPROVED_COUNT,
    COUNT(CASE WHEN STATUS = 'REFUNDED' THEN 1 END) AS REFUNDED_COUNT
FROM SILVER_CLEANED_TRANSACTIONS
WHERE MERCHANT_NAME = 'TechZone'
GROUP BY MERCHANT_NAME;


--=========TASK 6
SELECT
    SUM(RAW_BRONZE:amount::NUMBER(12,2))    AS BRONZE_GROSS_SUM,
    SUM(S.GROSS_AMOUNT)                     AS SILVER_GROSS_SUM,
    SUM(G.TOTAL_APPROVED_GROSS)             AS GOLD_GROSS_SUM,
    CASE
        WHEN SUM(RAW_BRONZE:amount::NUMBER(12,2)) = SUM(S.GROSS_AMOUNT)
        THEN 'TRUE'
        ELSE 'FALSE'
    END                                     AS DATA_MATCH_FLAG
FROM BRONZE_PAYMENT_PAYLOADS B
CROSS JOIN (SELECT SUM(GROSS_AMOUNT) AS GROSS_AMOUNT FROM SILVER_CLEANED_TRANSACTIONS) S
CROSS JOIN (SELECT SUM(TOTAL_APPROVED_GROSS) AS TOTAL_APPROVED_GROSS FROM GOLD_MERCHANT_SETTLEMENTS) G;