-- ============================================================
-- PROJECT 19A: E-Commerce Sales, Snapshot Inventory & Lifecycle


CREATE WAREHOUSE P19A_WH
WAREHOUSE_SIZE = 'X-SMALL';
USE WAREHOUSE P19A_WH;
CREATE DATABASE P19A_DB;
USE DATABASE P19A_DB;
CREATE SCHEMA P19A_SCHEMA;
USE SCHEMA P19A_SCHEMA;


CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null');

CREATE OR REPLACE STAGE P19A_STAGE
FILE_FORMAT = CSV_FORMAT;

SHOW STAGES;
SHOW FILE FORMATS;

LIST @P19A_STAGE;

--------------------------TASK 1------------------------------

CREATE OR REPLACE TABLE RAW_ORDERS (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    USER_ID VARCHAR,
    STORE_ID VARCHAR,
    AMOUNT NUMBER(10,2),
    TAX NUMBER(10,2),
    PAYMENT_METHOD VARCHAR,
    SHIPPING_OPTION VARCHAR,
    GIFT_WRAP_FLAG VARCHAR
);

COPY INTO RAW_ORDERS
FROM @P19A_STAGE/raw_orders.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT *
FROM RAW_ORDERS
ORDER BY ORDER_ID;

CREATE OR REPLACE TABLE DIM_ORDER_INDICATORS (
    INDICATOR_SK NUMBER AUTOINCREMENT,
    PAYMENT_METHOD VARCHAR,
    SHIPPING_OPTION VARCHAR,
    GIFT_WRAP_FLAG VARCHAR
);

INSERT INTO DIM_ORDER_INDICATORS
(
    PAYMENT_METHOD,
    SHIPPING_OPTION,
    GIFT_WRAP_FLAG
)
SELECT DISTINCT
    PAYMENT_METHOD,
    SHIPPING_OPTION,
    GIFT_WRAP_FLAG
FROM RAW_ORDERS;

SELECT *
FROM DIM_ORDER_INDICATORS
ORDER BY INDICATOR_SK;

----------------TASK 2--------------------------------

CREATE TABLE FACT_SALES_TRANSACTIONS
(
    ORDER_ID VARCHAR,              
    ORDER_DATE DATE,
    USER_ID VARCHAR,
    STORE_ID VARCHAR,
    INDICATOR_SK NUMBER,
    AMOUNT NUMBER(10,2),
    TAX NUMBER(10,2)
);

INSERT INTO FACT_SALES_TRANSACTIONS
(
    ORDER_ID,
    ORDER_DATE,
    USER_ID,
    STORE_ID,
    INDICATOR_SK,
    AMOUNT,
    TAX
)
SELECT
    R.ORDER_ID,
    R.ORDER_DATE,
    R.USER_ID,
    R.STORE_ID,
    D.INDICATOR_SK,
    R.AMOUNT,
    R.TAX
FROM RAW_ORDERS R
JOIN DIM_ORDER_INDICATORS D
    ON R.PAYMENT_METHOD = D.PAYMENT_METHOD
   AND R.SHIPPING_OPTION = D.SHIPPING_OPTION
   AND R.GIFT_WRAP_FLAG = D.GIFT_WRAP_FLAG;

SELECT * FROM FACT_SALES_TRANSACTIONS;

----------------TASK 3----------------------------------
CREATE OR REPLACE TABLE RAW_INVENTORY (
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QTY_ON_HAND NUMBER,
    UNIT_COST NUMBER(10,2)
);
COPY INTO RAW_INVENTORY
FROM @P19A_STAGE/raw_inventory.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);
SELECT *
FROM RAW_INVENTORY
ORDER BY SNAPSHOT_DATE, STORE_ID, PRODUCT_ID;


CREATE TABLE FACT_INVENTORY_SNAPSHOT
(
    SNAPSHOT_DATE DATE,
    STORE_ID VARCHAR,
    TOTAL_UNITS_HELD NUMBER,
    TOTAL_INVENTORY_VAL NUMBER(12,2)
);
INSERT INTO FACT_INVENTORY_SNAPSHOT
(
    SNAPSHOT_DATE,
    STORE_ID,
    TOTAL_UNITS_HELD,
    TOTAL_INVENTORY_VAL
)
SELECT
    SNAPSHOT_DATE,
    STORE_ID,
    SUM(QTY_ON_HAND) AS TOTAL_UNITS_HELD,
    SUM(QTY_ON_HAND * UNIT_COST) AS TOTAL_INVENTORY_VAL
FROM RAW_INVENTORY
GROUP BY    
    SNAPSHOT_DATE,
    STORE_ID;

SELECT *
FROM FACT_INVENTORY_SNAPSHOT
ORDER BY SNAPSHOT_DATE, STORE_ID;

---------------TASK 4---------------------------
CREATE OR REPLACE TABLE RAW_FULFILLMENT (
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE
);
COPY INTO RAW_FULFILLMENT
FROM @P19A_STAGE/raw_fulfillment.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);
SELECT *
FROM RAW_FULFILLMENT
ORDER BY ORDER_ID;

CREATE TABLE FACT_ORDER_FULFILLMENT
(
    ORDER_ID VARCHAR,
    ORDER_DATE DATE,
    PICK_DATE DATE,
    SHIP_DATE DATE,
    DELIVERY_DATE DATE,
    PICK_LAG_DAYS NUMBER,
    SHIP_LAG_DAYS NUMBER,
    DELIVERY_LAG_DAYS NUMBER,
    TOTAL_FULFILLMENT_DAYS NUMBER
);
INSERT INTO FACT_ORDER_FULFILLMENT
(
    ORDER_ID,
    ORDER_DATE,
    PICK_DATE,
    SHIP_DATE,
    DELIVERY_DATE,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS
)
SELECT
    ORDER_ID,
    ORDER_DATE,
    PICK_DATE,
    SHIP_DATE,
    DELIVERY_DATE,
    DATEDIFF('DAY', ORDER_DATE, PICK_DATE) AS PICK_LAG_DAYS,
    DATEDIFF('DAY', PICK_DATE, SHIP_DATE) AS SHIP_LAG_DAYS,
    DATEDIFF('DAY', SHIP_DATE, DELIVERY_DATE) AS DELIVERY_LAG_DAYS,
    DATEDIFF('DAY', ORDER_DATE, DELIVERY_DATE) AS TOTAL_FULFILLMENT_DAYS,
FROM RAW_FULFILLMENT;

SELECT
    ORDER_ID,
    PICK_LAG_DAYS,
    SHIP_LAG_DAYS,
    DELIVERY_LAG_DAYS,
    TOTAL_FULFILLMENT_DAYS
FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_LAG_DAYS IS NOT NULL
ORDER BY ORDER_ID;


------------------TASK 5-------------------------

SELECT
    ORDER_ID,
    ORDER_DATE,
    CASE
        WHEN PICK_DATE IS NULL THEN 'NOT_PICKED'
        WHEN SHIP_DATE IS NULL THEN 'PICKED_NOT_SHIPPED'
        WHEN DELIVERY_DATE IS NULL THEN 'SHIPPED_NOT_DELIVERED'
        ELSE 'DELIVERED'
    END AS CURRENT_STATUS
FROM FACT_ORDER_FULFILLMENT
WHERE DELIVERY_DATE IS NULL
ORDER BY ORDER_ID;

------------------TASK 6-------------------------
SELECT
    D.PAYMENT_METHOD,
    COUNT(F.ORDER_ID) AS TOTAL_ORDERS,
    SUM(F.AMOUNT) AS TOTAL_REVENUE
FROM FACT_SALES_TRANSACTIONS F
JOIN DIM_ORDER_INDICATORS D
    ON F.INDICATOR_SK = D.INDICATOR_SK
GROUP BY D.PAYMENT_METHOD
ORDER BY D.PAYMENT_METHOD;