-- INITIAL 
-- ============================================


CREATE WAREHOUSE P7_HEALTHCARE_WH
WAREHOUSE_SIZE = 'XSMALL';

CREATE DATABASE P7_HEALTHCARE_DB;

CREATE SCHEMA P7_HEALTHCARE_DB.HEALTHCARE_SCHEMA;

USE WAREHOUSE P7_HEALTHCARE_WH;

USE DATABASE P7_HEALTHCARE_DB;

USE SCHEMA HEALTHCARE_SCHEMA;

-- ============================================


CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1;

CREATE STAGE P7_HEALTHCARE_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @P7_HEALTHCARE_STAGE;

-RAW TABLES=======================================;
CREATE TABLE RAW_ADMISSIONS(
    ADMISSION_ID     VARCHAR,
    PATIENT_ID       VARCHAR,
    DOCTOR_ID        VARCHAR,
    HOSPITAL_ID      VARCHAR,
    DEPARTMENT_ID    VARCHAR,
    ADMISSION_DATE    DATE,
    DISCHARGE_DATE    DATE
);

CREATE TABLE RAW_PATIENTS(
    PATIENT_ID       VARCHAR,
    PATIENT_NAME     VARCHAR,
    GENDER           VARCHAR,
    CITY             VARCHAR,
    STATE            VARCHAR
);


CREATE TABLE RAW_DOCTORS(
    DOCTOR_ID        VARCHAR,
    DOCTOR_NAME      VARCHAR,
    SPECIALIZATION   VARCHAR
);


CREATE TABLE RAW_HOSPITALS(
    HOSPITAL_ID      VARCHAR,
    HOSPITAL_NAME    VARCHAR,
    CITY             VARCHAR,
    STATE            VARCHAR,
    REGION           VARCHAR
);


CREATE TABLE RAW_DEPARTMENTS(
    DEPARTMENT_ID    VARCHAR,
    DEPARTMENT_NAME  VARCHAR
);


CREATE TABLE RAW_TREATMENTS(
    TREATMENT_ID       VARCHAR,
    TREATMENT_NAME     VARCHAR,
    TREATMENT_CATEGORY VARCHAR
);


CREATE TABLE RAW_BILLING(
    ADMISSION_ID      VARCHAR,
    PATIENT_ID        VARCHAR,
    DOCTOR_ID         VARCHAR,
    HOSPITAL_ID       VARCHAR,
    DEPARTMENT_ID     VARCHAR,
    ADMISSION_DATE    DATE,
    DISCHARGE_DATE    DATE
);

--CSV LOADING======================

COPY INTO RAW_ADMISSIONS
FROM @P7_HEALTHCARE_STAGE/admissions.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_BILLING
FROM @P7_HEALTHCARE_STAGE/billings.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_PATIENTS
FROM @P7_HEALTHCARE_STAGE/patients.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RAW_DOCTORS
FROM @P7_HEALTHCARE_STAGE/doctors.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_HOSPITALS
FROM @P7_HEALTHCARE_STAGE/hospitals.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_DEPARTMENTS
FROM @P7_HEALTHCARE_STAGE/departments.csv
FILE_FORMAT = CSV_FORMAT;


COPY INTO RAW_TREATMENTS
FROM @P7_HEALTHCARE_STAGE/treatments.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM RAW_PATIENTS;
SELECT * FROM RAW_DOCTORS;
SELECT * FROM RAW_HOSPITALS;
SELECT * FROM RAW_DEPARTMENTS;
SELECT * FROM RAW_TREATMENTS;
SELECT * FROM RAW_ADMISSIONS;
SELECT * FROM RAW_BILLING;

--dim tables===============================================*/


CREATE TABLE DIM_PATIENT(
    PATIENT_KEY     NUMBER AUTOINCREMENT,
    PATIENT_ID       VARCHAR,
    PATIENT_NAME     VARCHAR,
    GENDER           VARCHAR,
    CITY             VARCHAR,
    STATE            VARCHAR,
    CONSTRAINT PK_DIM_PATIENT PRIMARY KEY(PATIENT_KEY)
);

CREATE TABLE DIM_DOCTOR(
    DOCTOR_KEY  NUMBER AUTOINCREMENT,
    DOCTOR_ID        VARCHAR,
    DOCTOR_NAME      VARCHAR,
    SPECIALIZATION   VARCHAR,
    CONSTRAINT PK_DIM_DOCTOR PRIMARY KEY(DOCTOR_KEY)
);

INSERT INTO DIM_PATIENT (
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
)
SELECT
    PATIENT_ID,
    PATIENT_NAME,
    GENDER,
    CITY,
    STATE
FROM RAW_PATIENTS;

SELECT * 
FROM DIM_PATIENT
ORDER BY PATIENT_KEY;

INSERT INTO DIM_DOCTOR(
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
)
SELECT
    DOCTOR_ID,
    DOCTOR_NAME,
    SPECIALIZATION
FROM RAW_DOCTORS;

CREATE TABLE DIM_HOSPITAL(
    HOSPITAL_KEY    NUMBER AUTOINCREMENT,
    HOSPITAL_ID     VARCHAR,
    HOSPITAL_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    REGION          VARCHAR,

    CONSTRAINT PK_DIM_HOSPITAL PRIMARY KEY (HOSPITAL_KEY)
);

INSERT INTO DIM_HOSPITAL(
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
)
SELECT
    HOSPITAL_ID,
    HOSPITAL_NAME,
    CITY,
    STATE,
    REGION
FROM RAW_HOSPITALS;

CREATE TABLE DIM_DEPARTMENT(
    DEPARTMENT_KEY    NUMBER AUTOINCREMENT,
    DEPARTMENT_ID     VARCHAR,
    DEPARTMENT_NAME   VARCHAR,

    CONSTRAINT PK_DIM_DEPARTMENT PRIMARY KEY (DEPARTMENT_KEY)
);

INSERT INTO DIM_DEPARTMENT(
    DEPARTMENT_ID,
    DEPARTMENT_NAME
)
SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME
FROM RAW_DEPARTMENTS;

CREATE TABLE DIM_TREATMENT(
    TREATMENT_KEY       NUMBER AUTOINCREMENT,
    TREATMENT_ID        VARCHAR,
    TREATMENT_NAME      VARCHAR,
    TREATMENT_CATEGORY  VARCHAR,

    CONSTRAINT PK_DIM_TREATMENT PRIMARY KEY (TREATMENT_KEY)
);

INSERT INTO DIM_TREATMENT(
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
)
SELECT
    TREATMENT_ID,
    TREATMENT_NAME,
    TREATMENT_CATEGORY
FROM RAW_TREATMENTS;


CREATE TABLE DIM_DATE(
    DATE_KEY       NUMBER,
    FULL_DATE      DATE,
    DAY            NUMBER,
    DAY_NAME       VARCHAR,
    WEEK_NO        NUMBER,
    MONTH          NUMBER,
    MONTH_NAME     VARCHAR,
    QUARTER        VARCHAR,
    YEAR           NUMBER,

    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY)
);

INSERT INTO DIM_DATE(
    DATE_KEY,
    FULL_DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    MONTH_NAME,
    QUARTER,
    YEAR
)
SELECT
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    DAY(FULL_DATE) AS DAY,
    DAYNAME(FULL_DATE) AS DAY_NAME,
    WEEK(FULL_DATE) AS WEEK_NO,
    MONTH(FULL_DATE) AS MONTH,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    'Q' || QUARTER(FULL_DATE) AS QUARTER,
    YEAR(FULL_DATE) AS YEAR
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2026-01-01'::DATE
    ) AS FULL_DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 90))
);

SELECT *FROM DIM_DATE;

/*========FACT TABLES==========================================*/

CREATE TABLE FACT_ADMISSION (
    ADMISSION_KEY      NUMBER AUTOINCREMENT,

    PATIENT_KEY        NUMBER,
    DOCTOR_KEY         NUMBER,
    HOSPITAL_KEY       NUMBER,
    DEPARTMENT_KEY     NUMBER,
    DATE_KEY           NUMBER,

    ADMISSION_COUNT    NUMBER,
    LENGTH_OF_STAY     NUMBER,

    CONSTRAINT PK_FACT_ADMISSION
        PRIMARY KEY (ADMISSION_KEY),

    CONSTRAINT FK_ADMISSION_PATIENT
        FOREIGN KEY (PATIENT_KEY)
        REFERENCES DIM_PATIENT(PATIENT_KEY),

    CONSTRAINT FK_ADMISSION_DOCTOR
        FOREIGN KEY (DOCTOR_KEY)
        REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    CONSTRAINT FK_ADMISSION_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_ADMISSION_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_KEY)
        REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    CONSTRAINT FK_ADMISSION_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);

INSERT INTO FACT_ADMISSION (
    PATIENT_KEY,
    DOCTOR_KEY,
    HOSPITAL_KEY,
    DEPARTMENT_KEY,
    DATE_KEY,
    ADMISSION_COUNT,
    LENGTH_OF_STAY
)
SELECT
    p.PATIENT_KEY,
    d.DOCTOR_KEY,
    h.HOSPITAL_KEY,
    dp.DEPARTMENT_KEY,
    dt.DATE_KEY,
    1 AS ADMISSION_COUNT,
    DATEDIFF(
        DAY,
        a.ADMISSION_DATE,
        a.DISCHARGE_DATE
    ) AS LENGTH_OF_STAY
FROM RAW_ADMISSIONS a

JOIN DIM_PATIENT p
    ON a.PATIENT_ID = p.PATIENT_ID

JOIN DIM_DOCTOR d
    ON a.DOCTOR_ID = d.DOCTOR_ID

JOIN DIM_HOSPITAL h
    ON a.HOSPITAL_ID = h.HOSPITAL_ID

JOIN DIM_DEPARTMENT dp
    ON a.DEPARTMENT_ID = dp.DEPARTMENT_ID

JOIN DIM_DATE dt
    ON a.ADMISSION_DATE = dt.FULL_DATE;

SELECT * FROM FACT_ADMISSION;

CREATE TABLE FACT_BILLING (
    BILLING_KEY        NUMBER AUTOINCREMENT,

    PATIENT_KEY        NUMBER,
    DOCTOR_KEY         NUMBER,
    HOSPITAL_KEY       NUMBER,
    DEPARTMENT_KEY     NUMBER,
    TREATMENT_KEY      NUMBER,
    DATE_KEY           NUMBER,

    QUANTITY           NUMBER,
    TREATMENT_AMOUNT   NUMBER,
    DISCOUNT           NUMBER,
    NET_AMOUNT         NUMBER,

    CONSTRAINT PK_FACT_BILLING
        PRIMARY KEY (BILLING_KEY),

    CONSTRAINT FK_BILLING_PATIENT
        FOREIGN KEY (PATIENT_KEY)
        REFERENCES DIM_PATIENT(PATIENT_KEY),

    CONSTRAINT FK_BILLING_DOCTOR
        FOREIGN KEY (DOCTOR_KEY)
        REFERENCES DIM_DOCTOR(DOCTOR_KEY),

    CONSTRAINT FK_BILLING_HOSPITAL
        FOREIGN KEY (HOSPITAL_KEY)
        REFERENCES DIM_HOSPITAL(HOSPITAL_KEY),

    CONSTRAINT FK_BILLING_DEPARTMENT
        FOREIGN KEY (DEPARTMENT_KEY)
        REFERENCES DIM_DEPARTMENT(DEPARTMENT_KEY),

    CONSTRAINT FK_BILLING_TREATMENT
        FOREIGN KEY (TREATMENT_KEY)
        REFERENCES DIM_TREATMENT(TREATMENT_KEY),

    CONSTRAINT FK_BILLING_DATE
        FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE(DATE_KEY)
);