/* PHASE 1-CREATING SNOWFLAKE ENVIRONMENT*/

CREATE WAREHOUSE RETIAL_WH
WAREHOUSE_SIZE='XSMALL';
USE WAREHOUSE RETIAL_WH;

CREATE DATABASE RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE SCHEMA SALES_SCHEMA;
USE SCHEMA SALES_SCHEMA;

SELECT CURRENT_WAREHOUSE(),
       CURRENT_DATABASE(),
       CURRENT_SCHEMA();

/*----------------------------*/

CREATE FILE FORMAT CSV_FORMAT
TYPE='CSV'
SKIP_HEADER=1
FIELD_DELIMITER=','
FIELD_OPTIONALLY_ENCLOSED_BY='"';

CREATE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT

SHOW STAGES;
/*---------------------------------------------*/
/*Phase 2 — Upload CSV Files*/

LIST @RETAIL_STAGE;

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INTEGER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    MEMBERSHIP VARCHAR
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    PRICE NUMBER(10,2)
);

CREATE TABLE BRANCHES (
    BRANCH_ID INTEGER,
    BRANCH_NAME VARCHAR,
    CITY VARCHAR
);

CREATE TABLE SALES (
    SALE_ID INTEGER,
    CUSTOMER_ID INTEGER,
    PRODUCT_ID INTEGER,
    BRANCH_ID INTEGER,
    QUANTITY INTEGER,
    SALE_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2)
);

SHOW TABLES;

COPY INTO CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM SALES;

/*Phase 3 — SQL Analytics*/
SELECT * FROM CUSTOMERS;
SELECT * FROM PRODUCTS;
SELECT * FROM BRANCHES;
SELECT * FROM SALES;

/*TOTAL BUSINESS REVENUE*/
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM SALES;

/*CUSTOMER WISE SAKES*/
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP
ORDER BY TOTAL_SPENDING DESC;

/*BRANCH WISE SALES*/
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY
ORDER BY TOTAL_REVENUE DESC;

/*PRODUCT WISE SALES*/
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    SUM(S.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

/*CATEGORY WISE SALES*/
SELECT
    P.CATEGORY,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

/*HIGHEST REVENUE BRANCH*/
SELECT
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY B.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

/*HIGHEST SPENDING CUSTOMER*/
SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 1;

/* TOP 3 PRODUCTS*/
SELECT
    P.PRODUCT_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
    ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 3;

/* TOP 3 CUMSTOMERS*/
SELECT
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC
LIMIT 3;

/*------------------------------------
PHASE 4 WINDOW FUNSTIONS
---------------------------------------*/
/*Rank Customers*/
SELECT
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS CUSTOMER_RANK
FROM CUSTOMERS C
JOIN SALES S
    ON C.CUSTOMER_ID = S.CUSTOMER_ID
GROUP BY
    C.CUSTOMER_ID,
    C.CUSTOMER_NAME
ORDER BY CUSTOMER_RANK;

/*Rank bRANCHES*/
SELECT
    B.BRANCH_ID,
    B.BRANCH_NAME,
    SUM(S.TOTAL_AMOUNT) AS TOTAL_SALES,
    RANK() OVER (
        ORDER BY SUM(S.TOTAL_AMOUNT) DESC
    ) AS BRANCH_RANK
FROM BRANCHES B
JOIN SALES S
    ON B.BRANCH_ID = S.BRANCH_ID
GROUP BY
    B.BRANCH_ID,
    B.BRANCH_NAME
ORDER BY BRANCH_RANK;

/*TOP SELLING PRODUCTS IN EACH CATEGORY*/
WITH PRODUCT_REVENUE AS (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM PRODUCTS P
    JOIN SALES S
        ON P.PRODUCT_ID = S.PRODUCT_ID
    GROUP BY
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        P.CATEGORY
)

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_REVENUE
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY CATEGORY
            ORDER BY TOTAL_REVENUE DESC
        ) AS RN
    FROM PRODUCT_REVENUE
)
WHERE RN = 1;

/*CUMULATIVE SALES*/
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (
        ORDER BY SALE_DATE, SALE_ID
    ) AS CUMULATIVE_SALES
FROM SALES
ORDER BY SALE_DATE, SALE_ID;


/*Calculate the average sale amount using AVG() OVER().*/
SELECT
    SALE_ID,
    SALE_DATE,
    TOTAL_AMOUNT,
    AVG(TOTAL_AMOUNT) OVER () AS AVERAGE_SALE_AMOUNT
FROM SALES
ORDER BY SALE_DATE;

/*------------------------------------
PHASE 5 CTE
---------------------------------------*/

/*Generate customer-wise revenue using a Common Table Expression (CTE).*/

WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
)

SELECT *
FROM CUSTOMER_REVENUE
ORDER BY TOTAL_REVENUE DESC;

/*Display customers whose spending is greater than the average spending.*/
WITH CUSTOMER_REVENUE AS (
    SELECT
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME,
        SUM(S.TOTAL_AMOUNT) AS TOTAL_SPENDING
    FROM CUSTOMERS C
    JOIN SALES S
        ON C.CUSTOMER_ID = S.CUSTOMER_ID
    GROUP BY
        C.CUSTOMER_ID,
        C.CUSTOMER_NAME
),

AVERAGE_SPENDING AS (
    SELECT
        AVG(TOTAL_SPENDING) AS AVG_SPENDING
    FROM CUSTOMER_REVENUE
)

SELECT
    CR.CUSTOMER_ID,
    CR.CUSTOMER_NAME,
    CR.TOTAL_SPENDING
FROM CUSTOMER_REVENUE CR
CROSS JOIN AVERAGE_SPENDING A
WHERE CR.TOTAL_SPENDING > A.AVG_SPENDING
ORDER BY CR.TOTAL_SPENDING DESC;

/*------------------------------------
PHASE 5 VIEWS
---------------------------------------*/

/*Create a View named SALES_REPORT.*/
CREATE OR REPLACE VIEW SALES_REPORT AS
SELECT
    S.SALE_ID,
    S.SALE_DATE,

    C.CUSTOMER_ID,
    C.CUSTOMER_NAME,
    C.MEMBERSHIP,

    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.CATEGORY,
    P.PRICE,

    B.BRANCH_ID,
    B.BRANCH_NAME,
    B.CITY AS BRANCH_CITY,

    S.QUANTITY,
    S.TOTAL_AMOUNT

FROM SALES S
JOIN CUSTOMERS C
    ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PRODUCTS P
    ON S.PRODUCT_ID = P.PRODUCT_ID
JOIN BRANCHES B
    ON S.BRANCH_ID = B.BRANCH_ID;
SELECT *
FROM SALES_REPORT;

/*Create a Materialized View named TOP_CUSTOMERS.*/
CREATE OR REPLACE MATERIALIZED VIEW TOP_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    SUM(TOTAL_AMOUNT) AS TOTAL_SPENDING
FROM SALES
GROUP BY CUSTOMER_ID;

SELECT *
FROM TOP_CUSTOMERS
ORDER BY TOTAL_SPENDING DESC;