CREATE WAREHOUSE P19b_WH
WAREHOUSE_SIZE='XSMALL';

CREATE DATABASE P19B_DB;
CREATE SCHEMA P19B_DB.P19B_SCHEMA;

USE WAREHOUSE P19B_WH;
USE DATABASE P19B_DB;
USE SCHEMA P19B_SCHEMA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('NULL', 'null');

CREATE STAGE P19B_STAGE
FILE_FORMAT = CSV_FORMAT;

show stages;

list @P19B_STAGE;

-----------------------------------------------
CREATE TABLE RAW_DOCTOR_ROSTER
(
    shift_date DATE,
    doctor_id VARCHAR,
    department_id VARCHAR,
    shift_type VARCHAR
);

COPY INTO RAW_DOCTOR_ROSTER
FROM @P19B_STAGE/raw_doctor_roster.csv
FILE_FORMAT = CSV_FORMAT;

CREATE TABLE RAW_PATIENT_JOURNEY
(
    encounter_id VARCHAR,
    patient_id VARCHAR,
    triage_date DATE,
    admission_date DATE,
    discharge_date DATE
);

COPY INTO RAW_PATIENT_JOURNEY
FROM @P19B_STAGE/raw_patient_journey.csv
FILE_FORMAT = CSV_FORMAT;

CREATE OR REPLACE TABLE RAW_TREATMENT_BILLS
(
    claim_id varchar,
    encounter_id varchar,
    patient_id varchar,
    procedure_cost number(12,2),
    insurance_discount_pct number(5,2),
    copay_amount number(12,2)
);

COPY INTO RAW_TREATMENT_BILLS
FROM @P19B_STAGE/raw_treatment_bills.csv
FILE_FORMAT = CSV_FORMAT;

select * from raw_treatment_bills;

-----------------------------TASK 1 -------------------------------

CREATE TABLE FACTLESS_STAFF_COVERAGE
(
    SHIFT_DATE DATE,
    DOCTOR_ID VARCHAR,
    DEPARTMENT_ID VARCHAR,
    SHIFT_TYPE VARCHAR    
);

INSERT INTO FACTLESS_STAFF_COVERAGE
(
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE 
)
SELECT
    SHIFT_DATE,
    DOCTOR_ID,
    DEPARTMENT_ID,
    SHIFT_TYPE 
FROM RAW_DOCTOR_ROSTER;

SELECT * FROM FACTLESS_STAFF_COVERAGE;

-----------TASK 2: Factless Coverage Analysis Query

SELECT
    DEPARTMENT_ID,
    COUNT(
        CASE
            WHEN SHIFT_TYPE='NIGHT'
            THEN 1
        END
    ) AS NIGHT_SHIFT_COUNT
FROM FACTLESS_STAFF_COVERAGE
WHERE SHIFT_DATE = '2026-08-20'
GROUP BY DEPARTMENT_ID
HAVING COUNT(
    CASE   
        WHEN SHIFT_TYPE = 'NIGHT' THEN 1
    END
) = 0;

---------------------------------TASK 3-------------------------------
CREATE TABLE FACT_PATIENT_ADMISSION_LIFECYCLE
(
    ENCOUNTER_ID VARCHAR,
    PATIENT_ID VARCHAR,
    TRIAGE_DATE DATE,
    ADMISSION_DATE DATE,
    DISCHARGE_DATE DATE,
    TRIAGE_TO_ADMIT_DAYS NUMBER,
    LENGTH_OF_STAY_DAYS NUMBER
);
INSERT INTO FACT_PATIENT_ADMISSION_LIFECYCLE
(
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
)
SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_DATE,
    ADMISSION_DATE,
    DISCHARGE_DATE,
    DATEDIFF('DAY', TRIAGE_DATE, ADMISSION_DATE) AS TRIAGE_TO_ADMIT_DAYS,
    DATEDIFF('DAY', ADMISSION_DATE, DISCHARGE_DATE) AS LENGTH_OF_STAY_DAYS
FROM RAW_PATIENT_JOURNEY;

SELECT
    ENCOUNTER_ID,
    PATIENT_ID,
    TRIAGE_TO_ADMIT_DAYS,
    LENGTH_OF_STAY_DAYS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE
WHERE ADMISSION_DATE IS NOT NULL
  AND DISCHARGE_DATE IS NOT NULL
ORDER BY ENCOUNTER_ID;
---------------------------------TASK 4-------------------------------

CREATE OR REPLACE TABLE FACT_TREATMENT_BILLING
(
    claim_id varchar,
    encounter_id varchar,
    patient_id varchar,
    procedure_cost number(12,2),
    insurance_discount_pct number(5,2),
    copay_amount number(12,2),
    NET_CHARGE NUMBER(12,2)
);

INSERT INTO FACT_TREATMENT_BILLING
(
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    NET_CHARGE
)
SELECT
    CLAIM_ID,
    ENCOUNTER_ID,
    PATIENT_ID,
    PROCEDURE_COST,
    INSURANCE_DISCOUNT_PCT,
    COPAY_AMOUNT,
    PROCEDURE_COST * (1-INSURANCE_DISCOUNT_PCT) - COPAY_AMOUNT AS NET_CHARGE
FROM
    RAW_TREATMENT_BILLS;

SELECT * FROM FACT_TREATMENT_BILLING;


SELECT * FROM RAW_TREATMENT_BILLS;

------------TASK 5---------------------------------

SELECT
    ENCOUNTER_ID,
    SUM(NET_CHARGE) AS TOTAL_NET_CHARGES,
    AVG(PROCEDURE_COST) AS AVG_PROCEDURE_COST
FROM FACT_TREATMENT_BILLING
GROUP BY ENCOUNTER_ID
ORDER BY ENCOUNTER_ID;

-------TASK 6-------------
SELECT
    L.ENCOUNTER_ID,
    L.PATIENT_ID,
    'NO_CLAIMS_ISSUED' AS UNBILLED_STATUS
FROM FACT_PATIENT_ADMISSION_LIFECYCLE L
LEFT JOIN FACT_TREATMENT_BILLING B
    ON L.ENCOUNTER_ID = B.ENCOUNTER_ID
WHERE B.CLAIM_ID IS NULL;