create or replace warehouse p9_data_wh
warehouse_size='xsmall';

CREATE DATABASE P9_CUSTOMER_SCD_DB;

CREATE SCHEMA P9_CUSTOMER_SCD_DB.P9_CUSTOMER_SCHEMA;

USE WAREHOUSE P9_DATA_WH;
USE DATABASE P9_CUSTOMER_SCD_DB;
USE SCHEMA P9_CUSTOMER_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE P9_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @P9_STAGE;

/*===================================================================*/

CREATE TABLE CUSTOMER_INITIAL_STAGE (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

COPY INTO CUSTOMER_INITIAL_STAGE
FROM @P9_STAGE/customer_inititals.csv
FILE_FORMAT = CSV_FORMAT;

SELECT *
FROM CUSTOMER_INITIAL_STAGE;

CREATE OR REPLACE TABLE CUSTOMER_UPDATES_STAGE (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE
);
COPY INTO CUSTOMER_UPDATES_STAGE
FROM @P9_STAGE/customer_updates.csv
FILE_FORMAT = CSV_FORMAT;

SELECT *
FROM CUSTOMER_UPDATES_STAGE;

/*========================SCd_type 1 dimension============================*/

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE1 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30)
);

INSERT INTO DIM_CUSTOMER_TYPE1 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM CUSTOMER_INITIAL_STAGE;

SELECT *
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;


/*===============TASK 4 — Apply SCD Type 1 Updates======================*/

UPDATE DIM_CUSTOMER_TYPE1 AS T
SET
    CUSTOMER_NAME = S.CUSTOMER_NAME,
    CITY=S.CITY,
    STATE=S.STATE,
    MEMBERSHIP=S.MEMBERSHIP,
    SEGMENT = S.SEGMENT
FROM CUSTOMER_UPDATES_STAGE AS S
WHERE T.CUSTOMER_ID=S.CUSTOMER_ID;

/*===============TASK 5 — DISPLAY SCD Type 1 Updates======================*/
SELECT *
FROM DIM_CUSTOMER_TYPE1
ORDER BY CUSTOMER_ID;

/*===============TASK 6 —  Demonstrate Type 1 History Loss======================*/
SELECT
    CUSTOMER_ID,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER_TYPE1
WHERE CUSTOMER_ID IN (101,103,104);

/*==========TASK 7-9 — Create SCD Type 2 Table=======================================*/

CREATE OR REPLACE TABLE DIM_CUSTOMER_TYPE2 (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

DESC TABLE DIM_CUSTOMER_TYPE2;

INSERT INTO DIM_CUSTOMER_TYPE2(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM CUSTOMER_INITIAL_STAGE;

SELECT *
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID;
/*================TASK 10-14 — Apply Type 2 Changes=================================*/
UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-03-31',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 101
  AND IS_CURRENT = TRUE;

  
INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES_STAGE
WHERE CUSTOMER_ID = 101;

SELECT *
FROM DIM_CUSTOMER_TYPE2
WHERE CUSTOMER_ID = 101
ORDER BY EFFECTIVE_DATE;
UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-04-04',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 103
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES_STAGE
WHERE CUSTOMER_ID = 103;

UPDATE DIM_CUSTOMER_TYPE2
SET
    EXPIRY_DATE = '2026-04-09',
    IS_CURRENT = FALSE
WHERE CUSTOMER_ID = 104
  AND IS_CURRENT = TRUE;

INSERT INTO DIM_CUSTOMER_TYPE2 (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    '9999-12-31',
    TRUE
FROM CUSTOMER_UPDATES_STAGE
WHERE CUSTOMER_ID = 104;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER_TYPE2
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

/*===================task 15=======================================*/

select
CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT

from dim_customer_type2
where is_current = true
order by customer_id;

/*================================TASK 16 — Historical Customer Analysis====================*/
select
    CUSTOMER_ID,
    CUSTOMER_NAME,
    MEMBERSHIP,
    city,
    effective_date,
    expiry_date
from dim_customer_type2
where 
    CUSTOMER_ID=101
    and
    effective_date <='2026-03-15'
    and expiry_date >='2026-03-15'
;

/*=====================task 17=============================================*/
SELECT
    'SCD TYPE 1' AS SCD_TYPE,
    'No' AS OLD_VALUE_PRESERVED,
    'No' AS NEW_ROW_CREATED,
    'No' AS HISTORICAL_ANALYSIS,
    'No' AS EFFECTIVE_DATE,
    'No' AS EXPIRY_DATE,
    'No' AS IS_CURRENT

UNION ALL

SELECT
    'SCD TYPE 2',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'Yes',
    'Yes';

/*==============================task 18 Final Validation===================================================*/
SELECT COUNT(*) AS SCD_TYPE1_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE1;

SELECT COUNT(*) AS SCD_TYPE2_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2;

SELECT COUNT(*) AS SCD_TYPE2_CURRENT_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = TRUE;

SELECT COUNT(*) AS SCD_TYPE2_HISTORICAL_RECORD_COUNT
FROM DIM_CUSTOMER_TYPE2
WHERE IS_CURRENT = FALSE;