
CREATE or replace WAREHOUSE P11_WH
WAREHOUSE_SIZE = 'XSMALL';

USE WAREHOUSE P11_WH;

CREATE or replace DATABASE P11_DB;

CREATE or replace SCHEMA P11_DB.P11_SCHEMA;

USE DATABASE P11_DB;
USE SCHEMA P11_SCHEMA;

CREATE or replace FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE P11_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @P11_STAGE;
SHOW STAGES IN SCHEMA P11_DB.P11_SCHEMA;

-- =====================================

create OR REPLACE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    PREVIOUS_CITY VARCHAR,
    STATE VARCHAR,
    CURRENT_MEMBERSHIP VARCHAR,
    PREVIOUS_MEMBERSHIP VARCHAR,
    HISTORICAL_MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR,
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);

INSERT INTO DIM_CUSTOMER(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1,
    $2,
    $3,
    NULL,
    $4,
    $5,
    NULL,
    $5,
    $6,
    '2026-01-01',
    '9999-12-31',
    TRUE
FROM @P11_STAGE/customers_initial.csv
(
    FILE_FORMAT => 'CSV_FORMAT'
);


--============TASK 4====================

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;
-- TASK 5 =======================================
UPDATE DIM_CUSTOMER
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM
(
    SELECT
        $1 AS CUSTOMER_ID,
        $7 AS EFFECTIVE_DATE
    FROM @P11_STAGE/customer_updates.csv
    (
        FILE_FORMAT=>'CSV_FORMAT'
    )
)U
WHERE DIM_CUSTOMER.CUSTOMER_ID = U.CUSTOMER_ID
  AND DIM_CUSTOMER.IS_CURRENT = TRUE;


INSERT INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    $1 AS CUSTOMER_ID,
    $2 AS CUSTOMER_NAME,
    $3 AS CITY,
    NULL AS PREVIOUS_CITY,
    $4 AS STATE,
    $5 AS CURRENT_MEMBERSHIP,
    NULL AS PREVIOUS_MEMBERSHIP,
    $5 AS HISTORICAL_MEMBERSHIP,
    $6 AS SEGMENT,
    $7 AS EFFECTIVE_DATE,
    '9999-12-31' AS EXPIRY_DATE,
    TRUE AS IS_CURRENT
FROM @P11_STAGE/customer_updates.csv
(
    FILE_FORMAT => 'CSV_FORMAT'
);

-- SYNCHRONIZE HYBRID ATTRIBUTES
--============================================
UPDATE DIM_CUSTOMER AS D
SET
    CITY                = NEW.CITY,
    PREVIOUS_CITY       = CASE
                              WHEN NEW.CITY <> OLD.CITY THEN OLD.CITY
                              ELSE D.PREVIOUS_CITY
                          END,
    STATE               = NEW.STATE,
    CURRENT_MEMBERSHIP  = NEW.MEMBERSHIP,
    PREVIOUS_MEMBERSHIP = OLD.MEMBERSHIP
FROM
(
    SELECT
        $1 AS CUSTOMER_ID,
        $3 AS CITY,
        $4 AS STATE,
        $5 AS MEMBERSHIP
    FROM @P11_STAGE/customer_updates.csv
    (FILE_FORMAT => 'CSV_FORMAT')
) AS NEW
JOIN
(
    SELECT CUSTOMER_ID, CITY, HISTORICAL_MEMBERSHIP AS MEMBERSHIP
    FROM DIM_CUSTOMER
    WHERE IS_CURRENT = FALSE
      AND EXPIRY_DATE <> '9999-12-31'
) AS OLD
    ON NEW.CUSTOMER_ID = OLD.CUSTOMER_ID
WHERE D.CUSTOMER_ID = NEW.CUSTOMER_ID;
-- TASK 6 — DISPLAY COMPLETE DIMENSION HISTORY
-- ============================================

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;


-- TASK 7 — Active Customer Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;


-- TASK 8 — Point-in-Time Historical Query (Customer 101 on March 15, 2026)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101
  AND '2026-03-15' BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- TASK 9 — Metric Validation and Record Counts
SELECT 'TOTAL RECORD COUNT'       AS METRIC, COUNT(*)                          AS VALUE FROM DIM_CUSTOMER
UNION ALL
SELECT 'CURRENT RECORD COUNT'     AS METRIC, COUNT(*)                          AS VALUE FROM DIM_CUSTOMER WHERE IS_CURRENT = TRUE
UNION ALL
SELECT 'HISTORICAL RECORD COUNT'  AS METRIC, COUNT(*)                          AS VALUE FROM DIM_CUSTOMER WHERE IS_CURRENT = FALSE;
