-- ============================================

CREATE WAREHOUSE RETAIL_WHP5
WAREHOUSE_SIZE = 'XSMALL';

USE WAREHOUSE RETAIL_WHP5;

CREATE DATABASE RETAIL_DWP5;

CREATE SCHEMA RETAIL_DWP5.RETAIL_SCHEMA;

CREATE SCHEMA RETAIL_DWP5.RETAIL_RAW;

USE DATABASE RETAIL_DWP5;
USE SCHEMA RETAIL_SCHEMA;

-- ============================================

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;

-- ============================================

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_STAGE;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_CUSTOMERS (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    MEMBERSHIP      VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_PRODUCTS (
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    BRAND           VARCHAR,
    PRICE           NUMBER(12,2)
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_BRANCHES (
    BRANCH_ID       NUMBER,
    BRANCH_NAME     VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    REGION          VARCHAR,
    MANAGER_NAME    VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_CALENDAR (
    DATE_ID         NUMBER,
    DATE            DATE,
    DAY             NUMBER,
    DAY_NAME        VARCHAR,
    WEEK_NO         NUMBER,
    MONTH           VARCHAR,
    QUARTER         VARCHAR,
    YEAR            NUMBER,
    IS_WEEKEND      VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_SALES (
    SALE_ID         NUMBER,
    CUSTOMER_ID     NUMBER,
    PRODUCT_ID      NUMBER,
    BRANCH_ID       NUMBER,
    DATE_ID         NUMBER,
    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2)
);

-- ============================================

COPY INTO RETAIL_RAW.RAW_CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_CALENDAR
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM RETAIL_RAW.RAW_CUSTOMERS;
SELECT * FROM RETAIL_RAW.RAW_PRODUCTS;
SELECT * FROM RETAIL_RAW.RAW_BRANCHES;
SELECT * FROM RETAIL_RAW.RAW_CALENDAR;
SELECT * FROM RETAIL_RAW.RAW_SALES;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_CUSTOMER (
    CUSTOMER_ID     NUMBER PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    MEMBERSHIP      VARCHAR
);

INSERT INTO RETAIL_SCHEMA.DIM_CUSTOMER
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM RETAIL_RAW.RAW_CUSTOMERS;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_PRODUCT (
    PRODUCT_ID      NUMBER PRIMARY KEY,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    BRAND           VARCHAR,
    PRICE           NUMBER(12,2)
);

INSERT INTO RETAIL_SCHEMA.DIM_PRODUCT
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    PRICE
FROM RETAIL_RAW.RAW_PRODUCTS;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_BRANCH (
    BRANCH_ID       NUMBER PRIMARY KEY,
    BRANCH_NAME     VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    REGION          VARCHAR,
    MANAGER_NAME    VARCHAR
);

INSERT INTO RETAIL_SCHEMA.DIM_BRANCH
SELECT
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE,
    REGION,
    MANAGER_NAME
FROM RETAIL_RAW.RAW_BRANCHES;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_DATE (
    DATE_ID         NUMBER PRIMARY KEY,
    DATE            DATE,
    DAY             NUMBER,
    DAY_NAME        VARCHAR,
    WEEK_NO         NUMBER,
    MONTH           VARCHAR,
    QUARTER         VARCHAR,
    YEAR            NUMBER,
    IS_WEEKEND      VARCHAR
);

INSERT INTO RETAIL_SCHEMA.DIM_DATE
SELECT
    DATE_ID,
    DATE,
    DAY,
    DAY_NAME,
    WEEK_NO,
    MONTH,
    QUARTER,
    YEAR,
    IS_WEEKEND
FROM RETAIL_RAW.RAW_CALENDAR;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.FACT_SALES (
    SALE_ID         NUMBER PRIMARY KEY,

    CUSTOMER_ID     NUMBER,
    PRODUCT_ID      NUMBER,
    BRANCH_ID       NUMBER,
    DATE_ID         NUMBER,

    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES RETAIL_SCHEMA.DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES RETAIL_SCHEMA.DIM_PRODUCT(PRODUCT_ID),

    FOREIGN KEY (BRANCH_ID)
        REFERENCES RETAIL_SCHEMA.DIM_BRANCH(BRANCH_ID),

    FOREIGN KEY (DATE_ID)
        REFERENCES RETAIL_SCHEMA.DIM_DATE(DATE_ID)
);

INSERT INTO RETAIL_SCHEMA.FACT_SALES
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM RETAIL_RAW.RAW_SALES;

SELECT * FROM RETAIL_SCHEMA.FACT_SALES;

SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_CUSTOMER;
SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_PRODUCT;
SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_BRANCH;
SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_DATE;
SELECT COUNT(*) FROM RETAIL_SCHEMA.FACT_SALES;

/*=============================
CUSTOMER-WISE SALES REPORT
==============================*/

SELECT
    c.CUSTOMER_NAME,
    c.STATE,
    c.MEMBERSHIP,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME, c.STATE, c.MEMBERSHIP
ORDER BY TOTAL_REVENUE DESC;

/*=============================
PRODUCT-WISE REVENUE REPORT
==============================*/

SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME, p.CATEGORY, p.BRAND
ORDER BY TOTAL_REVENUE DESC;

/*=============================
BRANCH-WISE REVENUE REPORT
==============================*/

SELECT
    b.BRANCH_NAME,
    b.CITY,
    b.STATE,
    b.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_NAME, b.CITY, b.STATE, b.REGION
ORDER BY TOTAL_REVENUE DESC;

/*=============================
STATE-WISE REVENUE REPORT
==============================*/

SELECT
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.STATE
ORDER BY TOTAL_REVENUE DESC;

/*=============================
MONTHLY REVENUE REPORT
==============================*/

SELECT
    d.YEAR,
    d.MONTH,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.MONTH
ORDER BY d.YEAR, d.MONTH;

/*=============================
QUARTERLY REVENUE REPORT
==============================*/

SELECT
    d.YEAR,
    d.QUARTER,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.QUARTER
ORDER BY d.YEAR, d.QUARTER;

/*=============================
TOP 10 CUSTOMERS
==============================*/

SELECT TOP 10
    c.CUSTOMER_NAME,
    c.MEMBERSHIP,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME, c.MEMBERSHIP
ORDER BY TOTAL_REVENUE DESC;

/*=============================
TOP 10 PRODUCTS
==============================*/

SELECT TOP 10
    p.PRODUCT_NAME,
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME, p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

/*=============================
TOP 10 PERFORMING BRANCHES
==============================*/

SELECT TOP 10
    b.BRANCH_NAME,
    b.REGION,
    b.MANAGER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_NAME, b.REGION, b.MANAGER_NAME
ORDER BY TOTAL_REVENUE DESC;

/*=============================
CATEGORY-WISE REVENUE
==============================*/

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

/*=============================
CUSTOMER PURCHASE TREND
==============================*/

SELECT
    c.CUSTOMER_NAME,
    d.YEAR,
    d.MONTH,
    COUNT(f.SALE_ID)    AS NUM_PURCHASES,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_SPEND
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_CUSTOMER c ON f.CUSTOMER_ID = c.CUSTOMER_ID
JOIN RETAIL_SCHEMA.DIM_DATE d     ON f.DATE_ID     = d.DATE_ID
GROUP BY c.CUSTOMER_NAME, d.YEAR, d.MONTH
ORDER BY c.CUSTOMER_NAME, d.YEAR, d.MONTH;

/*=============================
PRODUCT PERFORMANCE DASHBOARD
==============================*/

SELECT
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    SUM(f.QUANTITY)               AS TOTAL_UNITS_SOLD,
    SUM(f.TOTAL_AMOUNT)           AS TOTAL_REVENUE,
    COUNT(DISTINCT f.CUSTOMER_ID) AS UNIQUE_BUYERS
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME, p.CATEGORY, p.BRAND
ORDER BY TOTAL_REVENUE DESC;

/*=============================
BRANCH PERFORMANCE DASHBOARD
==============================*/

SELECT
    b.BRANCH_NAME,
    b.REGION,
    b.MANAGER_NAME,
    COUNT(f.SALE_ID)              AS TOTAL_TRANSACTIONS,
    SUM(f.TOTAL_AMOUNT)           AS TOTAL_REVENUE,
    COUNT(DISTINCT f.CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_NAME, b.REGION, b.MANAGER_NAME
ORDER BY TOTAL_REVENUE DESC;

/*=============================
REGIONAL SALES ANALYSIS
==============================*/

SELECT
    b.REGION,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.REGION
ORDER BY TOTAL_REVENUE DESC;

/*=============================
SALES TREND ANALYSIS
==============================*/

SELECT
    d.DATE,
    d.DAY_NAME,
    d.IS_WEEKEND,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE,
    COUNT(f.SALE_ID)    AS TOTAL_TRANSACTIONS
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.DATE, d.DAY_NAME, d.IS_WEEKEND
ORDER BY d.DATE;
