-- ============================================

CREATE WAREHOUSE RETAIL_WHP4
WAREHOUSE_SIZE = 'XSMALL';

USE WAREHOUSE RETAIL_WHP4;

CREATE DATABASE RETAIL_DWP4;

CREATE SCHEMA RETAIL_DWP4.RETAIL_SCHEMA;

CREATE SCHEMA RETAIL_DWP4.RETAIL_RAW;

USE DATABASE RETAIL_DWP4;
USE SCHEMA RETAIL_SCHEMA;

-- ============================================

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE;

-- ============================================

CREATE OR REPLACE STAGE RETAIL_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @RETAIL_STAGE;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_CUSTOMERS (
    CUSTOMER_ID     NUMBER,
    CUSTOMER_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    MEMBERSHIP      VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_PRODUCTS (
    PRODUCT_ID      NUMBER,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    BRAND           VARCHAR,
    PRICE           NUMBER(12,2)
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_BRANCHES (
    BRANCH_ID       NUMBER,
    BRANCH_NAME     VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    REGION          VARCHAR,
    MANAGER_NAME    VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_CALENDAR (
    DATE_ID         NUMBER,
    DATE            DATE,
    DAY             NUMBER,
    DAY_NAME        VARCHAR,
    WEEK_NO         NUMBER,
    MONTH           VARCHAR,
    QUARTER         VARCHAR,
    YEAR            NUMBER,
    IS_WEEKEND      VARCHAR
);

-- ============================================

CREATE OR REPLACE TABLE RETAIL_RAW.RAW_SALES (
    SALE_ID         NUMBER,
    CUSTOMER_ID     NUMBER,
    PRODUCT_ID      NUMBER,
    BRANCH_ID       NUMBER,
    DATE_ID         NUMBER,
    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2)
);

-- ============================================

COPY INTO RETAIL_RAW.RAW_CUSTOMERS
FROM @RETAIL_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_PRODUCTS
FROM @RETAIL_STAGE/products.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_BRANCHES
FROM @RETAIL_STAGE/branches.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_CALENDAR
FROM @RETAIL_STAGE/calendar.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO RETAIL_RAW.RAW_SALES
FROM @RETAIL_STAGE/sales.csv
FILE_FORMAT = CSV_FORMAT;

SELECT * FROM RETAIL_RAW.RAW_CUSTOMERS;
SELECT * FROM RETAIL_RAW.RAW_PRODUCTS;
SELECT * FROM RETAIL_RAW.RAW_BRANCHES;
SELECT * FROM RETAIL_RAW.RAW_CALENDAR;
SELECT * FROM RETAIL_RAW.RAW_SALES;

-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_CUSTOMER (
    CUSTOMER_ID     NUMBER PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR,
    CITY            VARCHAR,
    STATE           VARCHAR,
    MEMBERSHIP      VARCHAR
);

INSERT INTO RETAIL_SCHEMA.DIM_CUSTOMER
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM RETAIL_RAW.RAW_CUSTOMERS;



CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_PRODUCT (
    PRODUCT_ID      NUMBER PRIMARY KEY,
    PRODUCT_NAME    VARCHAR,
    CATEGORY        VARCHAR,
    BRAND           VARCHAR,
    PRICE           NUMBER(12,2)
);

INSERT INTO RETAIL_SCHEMA.DIM_PRODUCT
SELECT  
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    PRICE
FROM RETAIL_RAW.RAW_PRODUCTS;

CREATE TABLE RETAIL_SCHEMA.DIM_BRANCH(
    BRANCH_ID   NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR,
    CITY        VARCHAR,
    STATE       VARCHAR
);

INSERT INTO RETAIL_SCHEMA.DIM_BRANCH
SELECT  
    BRANCH_ID,
    BRANCH_NAME,
    CITY,
    STATE
FROM RETAIL_RAW.RAW_BRANCHES;

CREATE OR REPLACE TABLE RETAIL_SCHEMA.DIM_DATE (
    DATE_ID     NUMBER PRIMARY KEY,
    DATE        DATE,
    MONTH       VARCHAR,
    QUARTER     VARCHAR,
    YEAR        NUMBER
);
INSERT INTO RETAIL_SCHEMA.DIM_DATE
SELECT
    DATE_ID,
    DATE,
    MONTH,
    QUARTER,
    YEAR
FROM RETAIL_RAW.RAW_CALENDAR;

-- ============================================
-- STEP 10: FACT_SALES
-- ============================================

CREATE OR REPLACE TABLE RETAIL_SCHEMA.FACT_SALES (
    SALE_ID         NUMBER PRIMARY KEY,

    CUSTOMER_ID     NUMBER,
    PRODUCT_ID      NUMBER,
    BRANCH_ID       NUMBER,
    DATE_ID         NUMBER,

    QUANTITY        NUMBER,
    TOTAL_AMOUNT    NUMBER(12,2),

    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES RETAIL_SCHEMA.DIM_CUSTOMER(CUSTOMER_ID),

    FOREIGN KEY (PRODUCT_ID)
        REFERENCES RETAIL_SCHEMA.DIM_PRODUCT(PRODUCT_ID),

    FOREIGN KEY (BRANCH_ID)
        REFERENCES RETAIL_SCHEMA.DIM_BRANCH(BRANCH_ID),

    FOREIGN KEY (DATE_ID)
        REFERENCES RETAIL_SCHEMA.DIM_DATE(DATE_ID)
);

INSERT INTO RETAIL_SCHEMA.FACT_SALES
SELECT
    SALE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    BRANCH_ID,
    DATE_ID,
    QUANTITY,
    TOTAL_AMOUNT
FROM RETAIL_RAW.RAW_SALES;

select * from retail_schema.FACT_SALES;

SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_CUSTOMER;

SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_PRODUCT;

SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_BRANCH;

SELECT COUNT(*) FROM RETAIL_SCHEMA.DIM_DATE;

SELECT COUNT(*) FROM RETAIL_SCHEMA.FACT_SALES;


/*=============================
CUSTOMER REVENUE=================*/

SELECT
    c.CUSTOMER_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_CUSTOMER c
    ON f.CUSTOMER_ID = c.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.PRODUCT_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.BRANCH_NAME,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.BRANCH_NAME
ORDER BY TOTAL_REVENUE DESC;

SELECT
    b.STATE,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_BRANCH b
    ON f.BRANCH_ID = b.BRANCH_ID
GROUP BY b.STATE
ORDER BY TOTAL_REVENUE DESC;

SELECT
    p.CATEGORY,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_PRODUCT p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

SELECT 
    d.YEAR,
    d.MONTH,
    SUM(f.TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_SCHEMA.FACT_SALES f
JOIN RETAIL_SCHEMA.DIM_DATE d
    ON f.DATE_ID = d.DATE_ID
GROUP BY d.YEAR, d.MONTH
ORDER BY d.YEAR, d.MONTH;
