CREATE WAREHOUSE CUSTOMER_SCD_WH
WAREHOUSE_SIZE = 'XSMALL';

CREATE DATABASE CUSTOMER_SCD_DB;

CREATE SCHEMA CUSTOMER_SCD_DB.CUSTOMER_SCHEMA;

USE WAREHOUSE CUSTOMER_SCD_WH;
USE DATABASE CUSTOMER_SCD_DB;
USE SCHEMA CUSTOMER_SCHEMA;

CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE CUSTOMER_STAGE
FILE_FORMAT = CSV_FORMAT;

LIST @CUSTOMER_STAGE;

/*==============================================*/

CREATE TABLE DIM_CUSTOMER
(
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);
COPY INTO DIM_CUSTOMER
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
)
FROM
(
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    FROM @CUSTOMER_STAGE/customers_initial.csv
)
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

CREATE TABLE CUSTOMER_UPDATES
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    MEMBERSHIP VARCHAR,
    SEGMENT VARCHAR
);

COPY INTO CUSTOMER_UPDATES
FROM @CUSTOMER_STAGE/customer_updates.csv
file_FORMAT = CSV_FORMAT;

SELECT *FROM CUSTOMER_UPDATES;

/*============================================================*/

SELECT 
    d.customer_id,
    d.city as old_city,
    u.city as new_city,
    d.membership as old_membership,
    u.membership as new_membership
from dim_customer d
join customer_updates u
    on d.customer_id = u.customer_id
where 
    d.city <> u.city
    or d.state <> u.state
    or d.membership <> u.membership
    or d.segment <> u.segment    
order by d.customer_id;

/*======task 7=========================*/
SELECT
    d.CUSTOMER_ID,
    'CITY' AS ATTRIBUTE,
    d.CITY AS OLD_VALUE,
    u.CITY AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.CITY <> u.CITY

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'STATE' AS ATTRIBUTE,
    d.STATE AS OLD_VALUE,
    u.STATE AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.STATE <> u.STATE

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'MEMBERSHIP' AS ATTRIBUTE,
    d.MEMBERSHIP AS OLD_VALUE,
    u.MEMBERSHIP AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.MEMBERSHIP <> u.MEMBERSHIP

UNION ALL

SELECT
    d.CUSTOMER_ID,
    'SEGMENT' AS ATTRIBUTE,
    d.SEGMENT AS OLD_VALUE,
    u.SEGMENT AS NEW_VALUE
FROM DIM_CUSTOMER d
JOIN CUSTOMER_UPDATES u
    ON d.CUSTOMER_ID = u.CUSTOMER_ID
WHERE d.SEGMENT <> u.SEGMENT

ORDER BY CUSTOMER_ID, ATTRIBUTE;

/*=======task 8======================*/

UPDATE DIM_CUSTOMER d
SET
    CUSTOMER_NAME = u.CUSTOMER_NAME,
    CITY = u.CITY,
    STATE = u.STATE,
    MEMBERSHIP = u.MEMBERSHIP,
    SEGMENT = u.SEGMENT
FROM CUSTOMER_UPDATES u
WHERE d.CUSTOMER_ID = u.CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP,
    SEGMENT
FROM DIM_CUSTOMER
ORDER BY CUSTOMER_ID;

SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    MEMBERSHIP
FROM DIM_CUSTOMER
WHERE CUSTOMER_ID = 101;